const MEDIUM_SCIENCE = [
  ['¿Qué gas representa cerca del 78% del aire seco?', 'nitrógeno', ['oxígeno', 'dióxido de carbono', 'hidrógeno'], 'El nitrógeno es el gas más abundante de la atmósfera seca.'],
  ['¿A qué temperatura Celsius hierve el agua a nivel del mar?', '100 °C', ['0 °C', '37 °C', '80 °C'], 'A presión normal el agua hierve a 100 °C.'],
  ['¿A qué temperatura Celsius se congela el agua pura?', '0 °C', ['-10 °C', '4 °C', '32 °C'], 'El punto de fusión del hielo es 0 °C.'],
  ['¿Cuál es el planeta más grande del sistema solar?', 'Júpiter', ['Saturno', 'Neptuno', 'Urano'], 'Júpiter es un gigante gaseoso mayor que los demás planetas.'],
  ['¿Qué planeta es conocido como el planeta rojo?', 'Marte', ['Venus', 'Mercurio', 'Júpiter'], 'Marte debe su color a óxidos de hierro en el suelo.'],
  ['¿Qué planeta es famoso por un sistema de anillos muy visible?', 'Saturno', ['Marte', 'Venus', 'Mercurio'], 'Los anillos de Saturno son de hielo y roca.'],
  ['¿Cuántos planetas tiene el sistema solar?', '8', ['7', '9', '12'], 'Desde 2006 Plutón se clasifica como planeta enano.'],
  ['¿Qué astro es una estrella y no un planeta?', 'el Sol', ['la Luna', 'Marte', 'Titán'], 'El Sol es la estrella del sistema solar.'],
  ['¿Qué satélite natural orbita la Tierra?', 'la Luna', ['Fobos', 'Europa', 'Ganimedes'], 'La Luna es el único satélite natural de la Tierra.'],
  ['¿Qué orgánulo vegetal captura la luz para hacer fotosíntesis?', 'el cloroplasto', ['la mitocondria', 'el ribosoma', 'el lisosoma'], 'La clorofila está en los cloroplastos.'],
  ['¿Qué orgánulo produce la mayor parte de la energía de la célula animal?', 'la mitocondria', ['el cloroplasto', 'la vacuola', 'el centriolo'], 'La respiración celular ocurre sobre todo en mitocondrias.'],
  ['¿Qué molécula guarda la información hereditaria?', 'el ADN', ['la glucosa', 'el ATP', 'la clorofila'], 'El ADN contiene los genes.'],
  ['¿Cuántas patas tiene un insecto adulto típico?', '6', ['4', '8', '10'], 'Los insectos tienen tres pares de patas.'],
  ['¿Cuántas patas tiene una araña?', '8', ['6', '4', '10'], 'Las arañas son arácnidos, no insectos.'],
  ['¿Qué fuerza mantiene a la Luna en órbita alrededor de la Tierra?', 'la gravedad', ['el magnetismo terrestre solo', 'la fricción del aire', 'la inercia sin fuerza'], 'La gravedad es una atracción mutua entre masas.'],
  ['¿Qué metal es líquido a temperatura ambiente?', 'el mercurio', ['el hierro', 'el cobre', 'el aluminio'], 'El mercurio es líquido cerca de 20 °C.'],
  ['¿De qué elementos está formada la molécula de agua?', 'hidrógeno y oxígeno', ['sodio y cloro', 'carbono y nitrógeno', 'hierro y azufre'], 'H2O tiene dos hidrógenos y un oxígeno.'],
  ['¿Qué pH se considera neutro?', '7', ['0', '3', '14'], 'El agua pura está cerca de pH 7.'],
  ['¿El pH del limón es, en general…?', 'ácido, menor que 7', ['básico, mayor que 7', 'exactamente 7', 'exactamente 14'], 'Los cítricos son ácidos.'],
  ['¿Qué aparato sirve para ver células y microorganismos?', 'el microscopio', ['el telescopio', 'el barómetro', 'el sismógrafo'], 'El microscopio aumenta objetos diminutos.'],
  ['¿Qué aparato se usa para observar planetas y estrellas?', 'el telescopio', ['el microscopio', 'el termómetro', 'el amperímetro'], 'El telescopio recolecta luz lejana.'],
  ['¿Qué instrumento señala el norte magnético?', 'la brújula', ['el termómetro', 'el barómetro', 'el odómetro'], 'La aguja de la brújula se alinea al campo magnético.'],
  ['¿Qué miden los grados Celsius en un termómetro clínico?', 'la temperatura', ['la presión arterial', 'el peso', 'la humedad'], 'El termómetro mide temperatura.'],
  ['¿Qué fenómeno forma un arcoíris cuando la luz atraviesa gotas de agua?', 'la refracción y reflexión', ['la oxidación', 'la fermentación', 'la sublimación'], 'La luz se desvía y se descompone en colores.'],
  ['¿Qué material fundido sale de un volcán en erupción?', 'lava o magma', ['petróleo frío', 'nieve compacta', 'arena de desierto'], 'El magma en superficie se llama lava.'],
  ['¿Qué tipo de animal amamanta a sus crías?', 'un mamífero', ['un reptil', 'un anfibio', 'un pez óseo'], 'La leche es un rasgo de los mamíferos.'],
  ['¿Cómo respiran la mayoría de los peces?', 'por branquias', ['por pulmones como los humanos', 'por la piel solamente', 'por tráqueas de insecto'], 'Las branquias extraen oxígeno del agua.'],
  ['¿Qué vertebrados suelen nacer en el agua y luego vivir también en tierra?', 'los anfibios', ['las aves', 'los reptiles del desierto', 'los mamíferos marinos'], 'Ranas y salamandras son anfibios.'],
  ['¿Qué hueso es el más largo del cuerpo humano?', 'el fémur', ['el húmero', 'la tibia', 'el radio'], 'El fémur está en el muslo.'],
  ['¿Qué órgano bombea la sangre?', 'el corazón', ['el hígado', 'el páncreas', 'el riñón'], 'El corazón impulsa la circulación.'],
  ['¿Qué órgano controla el pensamiento y los sentidos?', 'el cerebro', ['el estómago', 'el bazo', 'la vesícula'], 'El cerebro es el centro del sistema nervioso.'],
  ['¿Qué células de la sangre transportan la mayor parte del oxígeno?', 'los glóbulos rojos', ['las plaquetas', 'los glóbulos blancos', 'las neuronas'], 'Los eritrocitos llevan hemoglobina.'],
  ['¿Para qué sirve principalmente una vacuna?', 'prevenir enfermedades', ['romper huesos', 'medir la fiebre', 'reemplazar el oxígeno'], 'Las vacunas entrenan al sistema inmune.'],
  ['¿Un antibiótico está pensado sobre todo para tratar…?', 'infecciones bacterianas', ['todas las infecciones virales', 'fracturas', 'alergias al polen siempre'], 'Los virus no se tratan igual que las bacterias.'],
  ['¿Qué describe mejor un año terrestre?', 'una órbita de la Tierra alrededor del Sol', ['una rotación de la Tierra', 'un ciclo de la Luna', 'un eclipse'], 'El año dura esa traslación.'],
  ['¿Por qué hay día y noche?', 'porque la Tierra rota sobre su eje', ['porque la Luna tapa el Sol cada día', 'porque la Tierra se aleja del Sol cada noche', 'porque Marte proyecta sombra'], 'La rotación dura unas 24 horas.'],
  ['¿Qué provoca principalmente las estaciones del año?', 'la inclinación del eje terrestre', ['la distancia a la Luna', 'el color de los océanos', 'el número de continentes'], 'El eje inclinado cambia cuánta luz recibe cada hemisferio.'],
  ['¿En un eclipse solar, qué astro se interpone?', 'la Luna entre la Tierra y el Sol', ['Marte entre la Tierra y el Sol', 'Júpiter detrás de la Luna', 'Venus detrás de la Tierra'], 'La Luna cubre el disco solar visto desde la Tierra.'],
  ['¿Qué provoca sobre todo las mareas oceánicas?', 'la gravedad de la Luna', ['el color del agua', 'los vientos alisios solamente', 'los volcanes submarinos siempre'], 'La Luna atrae las masas de agua.'],
  ['¿Qué es un fósil?', 'restos o huellas de seres del pasado', ['una roca recién formada en un laboratorio', 'un metal líquido', 'una nube de tormenta'], 'Los fósiles se conservan en rocas sedimentarias.'],
  ['¿En qué era vivieron la mayoría de los dinosaurios no avianos?', 'el Mesozoico', ['el Cenozoico humano', 'la Edad Media', 'el siglo XIX'], 'Triásico, Jurásico y Cretácico son del Mesozoico.'],
  ['¿Qué ecosistema frío de alta montaña es típico de los Andes colombianos?', 'el páramo', ['el arrecife de coral', 'el desierto sahariano', 'la tundra ártica de Groenlandia'], 'El páramo está por encima del bosque andino.'],
  ['¿Cuál es la selva tropical más extensa del mundo?', 'el Amazonas', ['el Congo solamente', 'Borneo solamente', 'la Taiga siberiana'], 'El Amazonas cubre varios países de Sudamérica.'],
  ['¿Qué océano es el de mayor superficie?', 'el Pacífico', ['el Atlántico', 'el Índico', 'el Ártico'], 'El Pacífico cubre más agua que cualquier otro.'],
  ['¿Cómo se llama el paso de agua líquida a vapor?', 'evaporación', ['condensación', 'solidificación', 'sublimación inversa'], 'Al calentarse, el agua se evapora.'],
  ['¿Cómo se llama el paso de vapor a líquido?', 'condensación', ['evaporación', 'fusión', 'combustión'], 'Así se forman las gotas de las nubes.'],
  ['¿Qué tres etapas principales tiene el ciclo del agua?', 'evaporación, condensación y precipitación', ['oxidación, fusión y eclipse', 'rotación, traslación y nutación', 'sismo, marea y magma'], 'El agua cambia de estado y de lugar.'],
  ['¿Qué parte de la planta absorbe agua y la sujeta al suelo?', 'la raíz', ['la flor', 'el fruto', 'el pétalo'], 'Las raíces también toman minerales.'],
  ['¿En qué parte de la planta ocurre gran parte de la fotosíntesis?', 'las hojas', ['las raíces profundas', 'las semillas secas', 'la corteza interior solamente'], 'Las hojas tienen cloroplastos.'],
  ['¿Un herbívoro se alimenta principalmente de…?', 'plantas', ['otros animales cazados', 'solo metales', 'solo hongos tóxicos'], 'Vacas y conejos son herbívoros.'],
  ['¿Un depredador se caracteriza por…?', 'cazar a otros animales', ['hacer fotosíntesis', 'comer solo piedras', 'no necesitar energía'], 'El depredador está arriba en la cadena alimentaria.'],
  ['¿Qué animal ayuda a polinizar muchas flores?', 'la abeja', ['el tiburón', 'el cóndor exclusivamente', 'el cangrejo de río'], 'Al buscar néctar lleva polen.'],
  ['¿Qué vitamina abunda en naranjas y limones?', 'la vitamina C', ['la vitamina D solar solamente', 'la vitamina K de la coagulación exclusivamente', 'la B12 de origen animal exclusivamente'], 'Los cítricos son fuente clásica de vitamina C.'],
  ['¿El calcio es especialmente importante para…?', 'huesos y dientes', ['el color del iris', 'la producción de lava', 'el magnetismo terrestre'], 'Una dieta con calcio ayuda al esqueleto.'],
  ['¿Qué energía aprovechan los paneles fotovoltaicos?', 'la luz del Sol', ['el viento de un molino', 'el calor interno de la Tierra solamente', 'el sonido de un trueno'], 'Las celdas convierten luz en electricidad.'],
  ['¿Qué energía aprovecha un aerogenerador?', 'el viento', ['la luz solar directa solamente', 'el uranio', 'las mareas exclusivamente'], 'Las aspas giran con el viento.'],
  ['¿Qué carga eléctrica tiene el electrón?', 'negativa', ['positiva', 'neutra', 'cambia cada segundo'], 'El protón es positivo; el electrón, negativo.'],
  ['¿Qué carga tiene el protón?', 'positiva', ['negativa', 'nula', 'magnética pura'], 'El protón está en el núcleo.'],
  ['¿Qué partícula del núcleo no tiene carga eléctrica?', 'el neutrón', ['el protón', 'el electrón', 'el fotón'], 'Neutrón viene de “neutro”.'],
  ['¿La densidad se define como…?', 'masa dividida entre volumen', ['velocidad entre tiempo', 'fuerza entre distancia', 'temperatura entre presión'], 'Un objeto denso pesa mucho en poco espacio.'],
  ['¿La energía cinética depende sobre todo de…?', 'el movimiento del objeto', ['solo su color', 'solo su sabor', 'solo su olor'], 'Si está quieto, su cinética es cero.'],
  ['¿Un objeto en lo alto tiene sobre todo…?', 'energía potencial gravitatoria', ['solo energía sonora', 'solo energía química de un imán', 'solo energía nuclear visible'], 'Al caer, esa energía se vuelve cinética.'],
  ['¿Qué fuerza se opone cuando frotamos dos superficies?', 'la fricción', ['la gravedad lunar solamente', 'el magnetismo de un imán de nevera', 'la tensión superficial del aire'], 'La fricción puede frenar o calentar.'],
  ['¿Qué capa atmosférica filtra gran parte de la radiación UV?', 'la capa de ozono', ['la troposfera de lluvia solamente', 'la ionosfera de auroras solamente', 'la exosfera'], 'El ozono estratosférico protege la vida.'],
  ['¿El efecto invernadero consiste en que ciertos gases…?', 'retienen calor en la atmósfera', ['apagan el Sol', 'congelan el núcleo terrestre', 'eliminan el oxígeno de golpe'], 'El CO2 y el metano retienen calor.'],
  ['¿Qué es la biodiversidad?', 'la variedad de seres vivos de un lugar', ['el número de ríos de un país', 'la altura de una montaña', 'el color de un desierto'], 'Más especies suelen hacer más estable un ecosistema.'],
  ['¿Dónde ocurre un sismo en la superficie, encima del origen?', 'en el epicentro', ['en el núcleo interno', 'en la estratosfera', 'en la Luna'], 'El hipocentro está en profundidad; el epicentro, arriba.'],
  ['¿Qué bloques de corteza se mueven y pueden causar terremotos?', 'las placas tectónicas', ['las nubes cumulonimbus', 'los cometas', 'las mareas rojas'], 'Los bordes de placa son zonas sísmicas.'],
  ['¿La Vía Láctea es…?', 'la galaxia donde está el sistema solar', ['un planeta enano', 'un océano de la Tierra', 'una constelación sola'], 'El Sol es una estrella de la Vía Láctea.'],
  ['¿Un cometa se caracteriza por…?', 'un núcleo de hielo y polvo con cola cerca del Sol', ['ser un satélite artificial', 'ser un tipo de pez', 'ser un volcán submarino'], 'El calor del Sol libera gas y polvo.'],
  ['¿Qué medio necesita el sonido para llegar a nuestros oídos?', 'un material como el aire', ['el vacío total del espacio', 'la oscuridad', 'el color rojo'], 'En el vacío no se propaga el sonido audible.'],
  ['¿Qué atrae de forma típica un imán?', 'objetos con hierro', ['la madera seca', 'el plástico', 'el vidrio limpio'], 'El ferromagnetismo es propio de algunos metales.'],
  ['¿La luz en un espejo liso principalmente…?', 'se refleja', ['se oxida', 'se evapora', 'se fermenta'], 'El ángulo de incidencia iguala al de reflexión.'],
  ['¿Reciclar papel ayuda sobre todo a…?', 'reducir el corte de árboles', ['aumentar la lava', 'secar los ríos de inmediato', 'crear más dióxido de silicio'], 'Se reutiliza la fibra de celulosa.'],
];

const MEDIUM_CULTURE = [
  ['¿Cuáles son los colores de la bandera de Colombia, de arriba hacia abajo?', 'amarillo, azul y rojo', ['rojo, blanco y azul', 'verde, blanco y rojo', 'azul y blanco'], 'El amarillo ocupa la franja superior más ancha.'],
  ['¿Cuál es el idioma oficial de Colombia?', 'español', ['portugués', 'inglés', 'francés'], 'El español es la lengua oficial mayoritaria.'],
  ['¿Cuál es la moneda de Colombia?', 'el peso', ['el dólar', 'el sol', 'el real'], 'Se usa el peso colombiano.'],
  ['¿Qué idioma se habla como oficial en Brasil?', 'portugués', ['español', 'francés', 'italiano'], 'Brasil es el gran país lusófono de América.'],
  ['¿Qué baile mestizo del Caribe es símbolo cultural colombiano?', 'la cumbia', ['el vals vienés', 'el flamenco andaluz', 'el tango finlandés'], 'La cumbia nació en la Costa Caribe.'],
  ['¿Qué ritmo de caja, guacharaca y acordeón es típico de la Costa Caribe?', 'el vallenato', ['el joropo llanero', 'el bambuco andino', 'el currulao del Pacífico'], 'El vallenato se asocia a Valledupar.'],
  ['¿Qué danza andina colombiana se acompaña a menudo con tiple?', 'el bambuco', ['la salsa cubana', 'el merengue dominicano', 'el reggae jamaiquino'], 'El bambuco es de la región andina.'],
  ['¿De qué región es típico el joropo?', 'los Llanos', ['el Pacífico chocoano', 'San Andrés', 'el altiplano cundiboyacense exclusivo'], 'El joropo se baila en los Llanos colombo-venezolanos.'],
  ['¿Qué ciudad colombiana es famosa por su Carnaval patrimonio de la UNESCO?', 'Barranquilla', ['Tunja', 'Manizales', 'Neiva'], 'El Carnaval de Barranquilla es patrimonio inmaterial.'],
  ['¿Dónde se celebra el Carnaval de Negros y Blancos?', 'Pasto', ['Valledupar', 'Montería', 'Florencia'], 'Es la fiesta grande de Nariño.'],
  ['¿Qué ciudad es sede de la Feria de las Flores?', 'Medellín', ['Cali', 'Bucaramanga', 'Ibagué'], 'Destaca el desfile de silleteros.'],
  ['¿Qué ciudad vallecaucana es conocida por su Feria de fin de año y la salsa?', 'Cali', ['Pereira', 'Villavicencio', 'Sincelejo'], 'Cali se asocia a la salsa y su feria.'],
  ['¿Qué festival de acordeón se realiza en Valledupar?', 'el Festival de la Leyenda Vallenata', ['Rock al Parque', 'el Carnaval de Negros y Blancos', 'la Feria de Manizales'], 'Es el gran encuentro del vallenato.'],
  ['¿Qué escritor colombiano escribió Cien años de soledad?', 'Gabriel García Márquez', ['Rafael Pombo', 'José Eustasio Rivera', 'Álvaro Mutis'], 'García Márquez ambientó gran parte de su obra en el Caribe.'],
  ['¿Qué pueblo ficticio creó García Márquez?', 'Macondo', ['Comala', 'Santa María de Onetta', 'Yoknapatawpha'], 'Macondo aparece en Cien años de soledad.'],
  ['¿En qué ciudad está el Museo del Oro del Banco de la República?', 'Bogotá', ['Cartagena', 'Cali', 'Medellín'], 'El museo reúne orfebrería prehispánica.'],
  ['¿Qué ciudad amurallada del Caribe es patrimonio mundial?', 'Cartagena', ['Santa Marta solamente moderna', 'Barranquilla', 'Riohacha'], 'El centro histórico está amurallado.'],
  ['¿Dónde está la Catedral de Sal?', 'Zipaquirá', ['Villa de Leyva', 'Guatavita', 'Honda'], 'Se excavó en las minas de sal de Cundinamarca.'],
  ['¿En qué departamento está el Santuario de Las Lajas?', 'Nariño', ['Huila', 'Cauca', 'Tolima'], 'Está cerca de Ipiales.'],
  ['¿Qué río de la Macarena es famoso por sus colores?', 'Caño Cristales', ['el Magdalena en Honda', 'el Cauca en Cali', 'el Amazonas en Leticia exclusivamente por los colores'], 'Las plantas acuáticas le dan tonos rojos y verdes.'],
  ['¿En qué departamento está el Desierto de la Tatacoa?', 'Huila', ['La Guajira', 'Boyacá', 'Meta'], 'Queda cerca de Villavieja.'],
  ['¿Qué pueblo indígena habita principalmente La Guajira?', 'los wayuu', ['los arhuacos de la Sierra solamente', 'los embera del Chocó solamente', 'los nasa del Cauca solamente'], 'Los wayuu son el pueblo indígena más numeroso del país.'],
  ['¿Qué sombrero trenzado es símbolo nacional?', 'el vueltiao', ['el bombín inglés', 'el chupalla', 'el cordobés español'], 'Se teje en Córdoba y Sucre.'],
  ['¿De qué región es típica la mochila wayuu?', 'La Guajira', ['el Eje Cafetero', 'el Amazonas de Leticia', 'San Andrés'], 'Es un tejido ancestral wayuu.'],
  ['¿Qué prenda de lana andina se usa en el frío de la cordillera?', 'la ruana', ['el kimono', 'el kilt', 'la pollera cueca'], 'La ruana cubre hombros y espalda.'],
  ['¿Qué plato bogotano lleva varias papas, pollo y mazorca?', 'el ajiaco', ['la bandeja paisa', 'el sancocho de sábana', 'el ceviche'], 'El ajiaco santafereño lleva guascas.'],
  ['¿De qué región es típica la bandeja paisa?', 'Antioquia', ['la Costa Caribe', 'los Llanos', 'el Pacífico'], 'Incluye frijoles, chicharrón y arepa.'],
  ['¿Natilla y buñuelos son típicos en Colombia sobre todo en…?', 'Navidad', ['Semana Santa solamente', 'el 20 de julio solamente', 'Halloween'], 'Se sirven en diciembre.'],
  ['¿Qué se celebra en Colombia el 7 de diciembre con luces?', 'el Día de las Velitas', ['el Día del Trabajo', 'Halloween', 'el Día de la Raza solamente'], 'Se honra a la Inmaculada Concepción.'],
  ['¿En qué fecha se conmemora la Independencia de Colombia (Grito de 1810)?', '20 de julio', ['7 de agosto', '1 de mayo', '12 de octubre'], 'El 20 de julio recuerda el Grito de Independencia.'],
  ['¿Qué organización declara patrimonios culturales de la humanidad?', 'la UNESCO', ['la FIFA', 'la NASA', 'la OPEP'], 'La UNESCO vela por el patrimonio mundial.'],
  ['¿Qué archipiélago colombiano tiene cultura raizal?', 'San Andrés y Providencia', ['Malpelo', 'Gorgona', 'las islas del Rosario'], 'Allí se habla también criollo e inglés.'],
  ['¿Qué bebida es el principal producto de exportación agrícola emblemático de Colombia?', 'el café', ['el tequila', 'el sake', 'el vodka'], 'El café suave de montaña es un símbolo nacional.'],
  ['¿Qué región es reconocida por el Paisaje Cultural Cafetero?', 'el Eje Cafetero', ['La Guajira', 'el Amazonas', 'San Andrés'], 'Caldas, Quindío, Risaralda y norte del Valle.'],
  ['¿San Basilio de Palenque es célebre por ser…?', 'el primer pueblo libre de América', ['la capital del vallenato', 'un puerto del Pacífico', 'un resguardo wayuu'], 'Fue fundado por cimarrones.'],
  ['¿La leyenda de El Dorado se asocia en Colombia sobre todo a…?', 'ofrendas muiscas en lagunas', ['un tesoro inca en el Cuzco solamente', 'pirámides mayas', 'minas de carbón inglesas'], 'La ceremonia del zipa inspiró el mito.'],
  ['¿Qué laguna de Cundinamarca se liga a El Dorado?', 'Guatavita', ['Tota solamente', 'La Cocha solamente', 'Fúquene solamente'], 'Allí se narran las ofrendas de oro.'],
  ['¿Qué lengua indígena andina se habla aún en varios países?', 'el quechua', ['el euskera', 'el galés', 'el bretón'], 'El quechua viene del Tahuantinsuyo.'],
  ['¿Qué comida de maíz es común en Colombia y Venezuela?', 'la arepa', ['el bagel', 'el croissant', 'el pretzel'], 'Se hace con masa de maíz.'],
  ['¿Qué infusión amarga es típica de Argentina y Uruguay?', 'el mate', ['el té matcha', 'el chai indio', 'el café turco'], 'Se toma en calabaza con bombilla.'],
  ['¿Qué plato peruano de pescado marinado es emblemático?', 'el ceviche', ['la paella', 'el mole', 'la feijoada'], 'El pescado se cura con limón o limón sutil.'],
  ['¿Qué música nació en Buenos Aires y Montevideo?', 'el tango', ['el flamenco', 'el fado', 'la samba de Río exclusivamente'], 'Es patrimonio del Río de la Plata.'],
  ['¿Qué danza y música afrobrasileña destaca en el carnaval de Río?', 'la samba', ['el vallenato', 'el joropo', 'el bambuco'], 'Las escuelas de samba desfilan en el sambódromo.'],
  ['¿El flamenco es un arte tradicional de…?', 'Andalucía, en España', ['la Costa Caribe colombiana', 'los Andes peruanos', 'el norte de México'], 'Junta cante, baile y toque de guitarra.'],
  ['¿Qué poeta chileno escribió Veinte poemas de amor y una canción desesperada?', 'Pablo Neruda', ['Gabriela Mistral en esa obra', 'Octavio Paz', 'César Vallejo'], 'Neruda fue Nobel de Literatura.'],
  ['¿Qué escritor peruano es autor de La ciudad y los perros?', 'Mario Vargas Llosa', ['Julio Cortázar', 'Jorge Luis Borges', 'Carlos Fuentes'], 'Vargas Llosa también recibió el Nobel.'],
  ['¿Qué civilización andina tuvo su capital en el Cuzco?', 'la inca', ['la azteca', 'la maya', 'la olmeca'], 'El Tahuantinsuyo se gobernó desde el Cuzco.'],
  ['¿Qué instrumento de viento andino se fabrica tradicionalmente de caña?', 'la quena', ['el saxofón', 'la gaita escocesa', 'el clarinete de jazz'], 'La quena es una flauta vertical.'],
  ['¿Leticia es capital de…?', 'el Amazonas colombiano', ['Boyacá', 'Caldas', 'Quindío'], 'Queda en la frontera con Brasil y Perú.'],
  ['¿La Sierra Nevada de Santa Marta está en…?', 'la Costa Caribe', ['el Pacífico sur', 'los Llanos orientales', 'la frontera con Ecuador'], 'Es la sierra costera más alta del mundo.'],
  ['¿Las islas del Rosario pertenecen al Caribe de…?', 'Colombia', ['Venezuela', 'Panamá', 'Nicaragua'], 'Están frente a Cartagena.'],
  ['¿Qué pueblo de la Sierra Nevada teje la mochila arhuaca?', 'los arhuacos', ['los wayuu', 'los embera', 'los tikuna'], 'La mochila tiene significado espiritual.'],
  ['¿El himno nacional es…?', 'la canción oficial de un país', ['un plato típico', 'un baile de salón', 'una moneda'], 'Se canta en actos solemnes.'],
  ['¿La globalización se refiere sobre todo a…?', 'la conexión económica y cultural entre países', ['un solo idioma mundial obligatorio', 'el fin de las banderas', 'una receta de sopa'], 'Personas, bienes e ideas circulan más rápido.'],
  ['¿Un patrimonio inmaterial protege sobre todo…?', 'tradiciones vivas, fiestas y saberes', ['solo edificios de piedra', 'solo minas', 'solo puentes'], 'La UNESCO también lista cantos, danzas y oficios.'],
  ['¿El mestizaje cultural en América describe…?', 'el encuentro de pueblos indígenas, europeos y africanos', ['el aislamiento total de cada cultura', 'solo la llegada de internet', 'un tratado de fútbol'], 'La comida, la música y la lengua muestran ese cruce.'],
  ['¿Qué ciudad colombiana alberga Rock al Parque?', 'Bogotá', ['Medellín', 'Cali', 'Barranquilla'], 'Es uno de los festivales de rock al aire libre más grandes de Latinoamérica.'],
  ['¿El Teatro Colón histórico de artes escénicas está en…?', 'Bogotá', ['Manizales', 'Pereira', 'Armenia'], 'Es una sala emblemática del centro de Bogotá.'],
  ['¿Qué bebida fermentada ancestral se conoce en varias culturas andinas?', 'la chicha', ['el sake japonés', 'el vodka', 'el whisky escocés'], 'Se prepara a menudo con maíz.'],
  ['¿El 12 de octubre se recuerda en varios países de América como…?', 'un día ligado al encuentro de dos mundos o a la diversidad étnica', ['el inicio de la Independencia de 1810 en Bogotá', 'el Día de las Velitas', 'la Batalla de Boyacá'], 'En Colombia se ha llamado Día de la Raza o de la Diversidad Étnica.'],
];

const MEDIUM_ART = [
  ['¿A qué familia de la orquesta pertenece el violín?', 'cuerdas', ['viento madera', 'viento metal', 'percusión'], 'El violín se frota con arco.'],
  ['¿Cuántas cuerdas tiene un violín estándar?', '4', ['3', '5', '6'], 'Se afinan en sol, re, la y mi.'],
  ['¿Con qué se frotan las cuerdas del violín?', 'un arco', ['un plectro', 'unas baquetas', 'unas macillas de piano'], 'El arco lleva crin tensada.'],
  ['¿El piano produce el sonido cuando las teclas activan…?', 'macillos que golpean cuerdas', ['un arco de violín', 'una lengüeta de saxofón', 'un parche de tambor'], 'Es un instrumento de teclado con cuerdas percutidas.'],
  ['¿La guitarra pertenece a la familia de…?', 'cuerdas pulsadas', ['viento metal', 'percusión de teclado', 'voces de coro'], 'Se pulsan las cuerdas con los dedos o una púa.'],
  ['¿Cuántas cuerdas tiene una guitarra clásica habitual?', '6', ['4', '8', '12'], 'Hay también versiones de 7 o 12, pero la clásica tiene 6.'],
  ['¿La flauta se clasifica como instrumento de…?', 'viento', ['cuerda frotada', 'percusión de membrana', 'teclado eléctrico'], 'El sonido nace al soplar.'],
  ['¿El tambor es un instrumento de…?', 'percusión', ['cuerda', 'viento madera', 'viento metal'], 'Se golpea un parche o caja.'],
  ['¿El saxofón se asocia sobre todo al…?', 'jazz y a las bandas de viento', ['canto gregoriano medieval', 'el ballet clásico del siglo XVI', 'la ópera de Monteverdi exclusivamente'], 'Lo inventó Adolphe Sax en el siglo XIX.'],
  ['¿El tiple colombiano se usa mucho en…?', 'música andina como el bambuco', ['el heavy metal noruego', 'el canto de ópera wagneriana', 'el hip hop de Nueva York exclusivamente'], 'Tiene 12 cuerdas agrupadas en cuatro órdenes.'],
  ['¿Cuáles son los tres colores primarios en pintura tradicional?', 'rojo, amarillo y azul', ['verde, naranja y morado', 'blanco, gris y negro', 'rosa, beige y dorado'], 'Con ellos se mezclan los secundarios.'],
  ['¿Qué color se obtiene al mezclar azul y amarillo?', 'verde', ['naranja', 'morado', 'marrón exclusivo siempre'], 'Es un secundario clásico.'],
  ['¿Qué color se obtiene al mezclar rojo y azul?', 'morado o violeta', ['verde', 'naranja', 'gris'], 'Rojo y azul dan un violeta.'],
  ['¿Qué color se obtiene al mezclar rojo y amarillo?', 'naranja', ['verde', 'violeta', 'azul'], 'Es el tercer secundario básico.'],
  ['¿Los colores complementarios están…?', 'opuestos en el círculo cromático', ['siempre uno al lado del otro', 'solo en blanco y negro', 'fuera de la luz visible'], 'Juntos contrastan con fuerza.'],
  ['¿El óleo se caracteriza por usar pigmentos con…?', 'aceite', ['solo agua', 'solo yema de huevo', 'solo cemento'], 'Seca más lento que la acuarela.'],
  ['¿La acuarela se diluye sobre todo con…?', 'agua', ['aceite de linaza', 'cera de auto', 'alcohol de quemar exclusivamente'], 'Es transparente y luminosa.'],
  ['¿Una escultura se diferencia de una pintura porque…?', 'ocupa tres dimensiones', ['solo usa palabras', 'solo usa sonidos', 'no puede representar personas'], 'Se puede rodear o tocar el volumen.'],
  ['¿Quién pintó la Mona Lisa?', 'Leonardo da Vinci', ['Miguel Ángel', 'Rafael', 'Botticelli'], 'Está en el Museo del Louvre.'],
  ['¿Quién pintó La noche estrellada?', 'Vincent van Gogh', ['Claude Monet', 'Paul Cézanne', 'Edvard Munch'], 'La pintó en 1889 en Saint-Rémy.'],
  ['¿Quién pintó el Guernica?', 'Pablo Picasso', ['Salvador Dalí', 'Joan Miró', 'Diego Rivera'], 'Denuncia el bombardeo de 1937.'],
  ['¿Las meninas es una obra de…?', 'Diego Velázquez', ['Francisco de Goya', 'El Greco', 'Murillo'], 'Retrata a la infanta Margarita en el Alcázar.'],
  ['¿El grito es una obra de…?', 'Edvard Munch', ['Gustav Klimt', 'Wassily Kandinsky', 'Paul Klee'], 'Es un ícono del expresionismo.'],
  ['¿El cubismo está ligado sobre todo a…?', 'Picasso y Braque', ['Monet y Renoir', 'Bach y Händel', 'Pelé y Maradona'], 'Fragmenta las formas en planos.'],
  ['¿El impresionismo buscaba sobre todo…?', 'captar la luz y el instante', ['copiar solo esculturas griegas', 'eliminar el color', 'pintar únicamente retratos reales'], 'Monet pintaba al aire libre.'],
  ['¿El surrealismo se asocia a sueños y a artistas como…?', 'Salvador Dalí', ['Miguel Ángel del David', 'Beethoven', 'Simón Bolívar'], 'Dalí pintó relojes blandos y paisajes oníricos.'],
  ['¿Fernando Botero es conocido por pintar y esculpir…?', 'figuras voluminosas', ['solo puntos abstractos', 'solo mapas estelares', 'solo letras tipográficas'], 'Ese estilo se llama boterismo.'],
  ['¿Frida Kahlo es especialmente famosa por sus…?', 'autorretratos', ['rascacielos', 'partituras de ópera', 'planos urbanísticos'], 'Convertía su vida y su cuerpo en tema.'],
  ['¿El David de Miguel Ángel es…?', 'una escultura de mármol', ['una ópera', 'un fresco del techo de la Sixtina exclusivamente en esta pregunta', 'un soneto'], 'Representa al David bíblico en Florencia.'],
  ['¿El Partenón es un templo de…?', 'la antigua Grecia, en Atenas', ['el Egipto de las pirámides', 'el Cuzco inca', 'la Roma del Coliseo exclusivamente'], 'Está en la Acrópolis.'],
  ['¿El Coliseo fue un anfiteatro de…?', 'la antigua Roma', ['Atenas clásica', 'Cartagena de Indias', 'Tenochtitlán'], 'Allí se hacían espectáculos públicos.'],
  ['¿Un bodegón representa sobre todo…?', 'objetos inanimados, como frutas o jarrones', ['batallas históricas', 'retratos de reyes', 'paisajes de montaña exclusivamente'], 'También se llama naturaleza muerta.'],
  ['¿Un retrato representa sobre todo…?', 'a una persona', ['un mapa político', 'una fórmula química', 'un eclipse'], 'Puede ser pictórico, escultórico o fotográfico.'],
  ['¿Un paisaje representa sobre todo…?', 'un lugar o una vista', ['un acorde musical', 'un hueso del cuerpo', 'un virus'], 'Puede ser real o imaginario.'],
  ['¿El arte abstracto se caracteriza por…?', 'no copiar la realidad de forma literal', ['ser solo fútbol fotografiado', 'ser solo recetas ilustradas', 'prohibir el color'], 'Usa formas, colores y ritmos propios.'],
  ['¿La perspectiva lineal sirve para…?', 'sugerir profundidad en un plano', ['borrar el color', 'apagar el sonido', 'medir un sismo'], 'Las líneas convergen en un punto de fuga.'],
  ['¿El claroscuro es el contraste de…?', 'luz y sombra', ['agudo y grave solamente en música', 'dulce y salado', 'rápido y lento en el cine'], 'Da volumen a las figuras.'],
  ['¿Un fresco se pinta sobre…?', 'el muro aún húmedo', ['papel de acuarela seca solamente', 'un lienzo encerado de auto', 'vidrio de reloj'], 'El pigmento se integra a la cal.'],
  ['¿Un collage se construye…?', 'pegando recortes y materiales sobre una superficie', ['tallando un solo bloque de mármol', 'soplando una flauta', 'revelando solo una foto analógica'], 'Puede incluir papel, tela o objetos.'],
  ['¿Un museo de arte sirve sobre todo para…?', 'conservar y mostrar obras', ['vender únicamente zapatos', 'reparar motores', 'cosechar trigo'], 'También investiga y educa.'],
  ['¿El lienzo es…?', 'la tela donde se pinta al óleo o acrílico', ['un tipo de balón', 'un casco de ciclismo', 'un remo'], 'Se tensa sobre un bastidor.'],
  ['¿La paleta del pintor sirve para…?', 'mezclar colores', ['medir terremotos', 'afinar un violín', 'dirigir el tráfico'], 'Puede ser de madera o de plástico.'],
  ['¿El caballete sirve para…?', 'sostener el cuadro mientras se pinta', ['escribir una partitura', 'tallar un sello', 'fundir un bronce'], 'Mantiene el lienzo a la altura de la vista.'],
  ['¿Una sinfonía está escrita sobre todo para…?', 'orquesta', ['un solista de guitarra eléctrica solamente', 'un coro infantil sin instrumentos', 'una banda de tejo'], 'Tiene varios movimientos.'],
  ['¿Un coro se forma con…?', 'varias voces cantando juntas', ['un solo tambor', 'un pincel', 'una cámara fotográfica'], 'Puede ser mixto, de cámara o infantil.'],
  ['¿La melodía es…?', 'una sucesión de notas que se reconocen como una frase', ['el color de un cuadro', 'el peso de una escultura', 'el tamaño de un escenario'], 'Se puede cantar o tocar.'],
  ['¿El ritmo en música organiza…?', 'el tiempo y los acentos', ['solo el color de los vestuarios', 'solo la altura del telón', 'solo el precio de las entradas'], 'Marca pulsos fuertes y débiles.'],
  ['¿El pentagrama tiene…?', 'cinco líneas', ['tres líneas', 'siete líneas', 'una sola línea'], 'Sobre él se escriben las notas.'],
  ['¿La clave de sol se usa mucho para…?', 'notas agudas, como la mano derecha del piano', ['indicar un penal', 'medir un sismo', 'nombrar un río'], 'Sitúa el sol en la segunda línea.'],
  ['¿Una ópera combina…?', 'canto, orquesta y drama escénico', ['solo atletismo', 'solo pintura mural', 'solo escultura en hielo'], 'Nació en Italia hacia 1600.'],
  ['¿El ballet es…?', 'una danza clásica escénica', ['un deporte de motor', 'un estilo de pintura rupestre', 'un tipo de grabado'], 'Usa posiciones y zapatillas específicas.'],
  ['¿La arquitectura se ocupa de…?', 'diseñar edificios y espacios', ['criar peces', 'estudiar cometas', 'escribir sonetos solamente'], 'Une función, técnica y estética.'],
  ['¿La fotografía captura imágenes mediante…?', 'la luz', ['el eco', 'el magnetismo de un imán de nevera', 'el sabor'], 'La cámara registra esa luz en un sensor o película.'],
  ['¿Guernica cuelga como símbolo antibélico y es de estilo…?', 'cubista', ['impresionista de Monet', 'romántico de Delacroix exclusivamente', 'fauvista de Matisse exclusivamente'], 'Picasso lo pintó en blanco, negro y gris.'],
  ['¿Alejandro Obregón fue un pintor…?', 'colombiano del arte moderno', ['belga del siglo XV', 'ruso del constructivismo exclusivo', 'piloto de Fórmula 1'], 'Pintó cóndores, el Caribe y la violencia.'],
  ['¿Débora Arango fue una…?', 'pintora colombiana de temas sociales', ['nadadora olímpica', 'física nuclear', 'chef francesa'], 'Retrató la política y la vida cotidiana.'],
  ['¿El muralismo se pinta sobre todo en…?', 'muros y paredes públicas', ['sellos de correo solamente', 'uñas', 'monedas diminutas'], 'Rivera, Orozco y Siqueiros lo impulsaron en México.'],
  ['¿Un mosaico se arma con…?', 'teselas o piezas pequeñas unidas', ['un solo bloque de hielo', 'una sola pincelada de óleo', 'un único hilo'], 'Fue habitual en Roma y Bizancio.'],
  ['¿La cerámica se obtiene al…?', 'cocer barro o arcilla', ['fundir solo oro', 'congelar nube', 'tejer lana'], 'El fuego endurece la pieza.'],
  ['¿La orfebrería trabaja sobre todo…?', 'metales preciosos como el oro y la plata', ['mármol de cantera exclusivamente', 'vidrio soplado exclusivamente', 'papel maché'], 'El Museo del Oro muestra orfebrería prehispánica.'],
  ['¿El director de orquesta sirve para…?', 'coordinar tempos y entradas de los músicos', ['árbitrar un penal', 'vender boletas', 'coser vestuario'], 'Usa la batuta frente a la orquesta.'],
  ['¿El telón de un teatro…?', 'cubre o descubre el escenario', ['afina los violines', 'mezcla óleos', 'escribe el libreto'], 'Se abre al empezar la función.'],
  ['¿Un libretto es…?', 'el texto de una ópera o zarzuela', ['un mapa de carreteras', 'una tabla periódica', 'un reglamento de básquet'], 'Narra la historia que se canta.'],
  ['¿El barroco se reconoce por un arte…?', 'recargado, dramático y con fuerte contraste', ['mínimo y geométrico como Mondrian solamente', 'solo fotográfico', 'solo digital'], 'Fue típico de los siglos XVII y principios del XVIII.'],
  ['¿Beethoven es autor, entre otras, de…?', 'la Quinta y la Novena sinfonías', ['el Guernica', 'Las meninas', 'el David de mármol'], 'La Novena incluye el Himno a la alegría.'],
  ['¿Mozart se asocia al estilo musical del…?', 'clasicismo', ['serialismo del siglo XX', 'reguetón', 'punk de los 70'], 'Compuso óperas, sinfonías y conciertos.'],
  ['¿Bach es un compositor clave del…?', 'barroco', ['impresionismo pictórico', 'cubismo', 'pop art'], 'Escribió fugas, cantatas y conciertos de Brandeburgo.'],
  ['¿La viola, frente al violín, suena en general…?', 'más grave', ['mucho más aguda que el flautín', 'igual que un tuba', 'igual que un bombo'], 'Es un poco más grande que el violín.'],
  ['¿El arpa se toca…?', 'punteando muchas cuerdas', ['soplando', 'golpeando un parche', 'frotando un arco único de violín'], 'Las pedales cambian la afinación.'],
  ['¿Un grabado se obtiene al imprimir…?', 'una placa o matriz entintada', ['un fresco húmedo directo en el muro', 'una acuarela que no se toca', 'una escultura de bronce'], 'Xilografía y aguafuerte son tipos de grabado.'],
  ['¿El arte precolombino de Colombia destaca por…?', 'orfebrería y cerámica', ['catedrales góticas', 'rascacielos de acero', 'pintura al óleo de caballete europeo'], 'Muiscas, taironas y quimbayas trabajaron el oro.'],
];

const MEDIUM_SPORTS = [
  ['¿Cuántos jugadores de un equipo de fútbol están en la cancha, incluido el arquero?', '11', ['9', '7', '15'], 'Se juega 11 contra 11.'],
  ['¿Cuánto dura el tiempo reglamentario de un partido de fútbol?', '90 minutos, en dos tiempos', ['60 minutos', '120 minutos fijos sin prórroga posible', '4 cuartos de 12 minutos'], 'Cada tiempo dura 45 minutos más el descuento.'],
  ['¿A qué distancia se cobra un penal en fútbol?', '11 metros', ['9 metros', '16,5 metros', '5 metros'], 'El punto penal está a 11 m de la portería.'],
  ['¿Una tarjeta roja en fútbol significa…?', 'expulsión', ['un saque de honor', 'un gol olímpico', 'un cambio obligatorio'], 'El equipo queda con un jugador menos.'],
  ['¿Una tarjeta amarilla es…?', 'una amonestación', ['un gol', 'un saque de meta', 'el final del partido'], 'Dos amarillas se convierten en roja.'],
  ['¿El fuera de juego sanciona sobre todo…?', 'una posición adelantada en el momento del pase', ['tocar el balón con la cabeza', 'un saque de banda', 'un cambio de portero'], 'El atacante no puede estar más cerca del arco que el penúltimo rival.'],
  ['¿Un córner se cobra desde…?', 'la esquina del campo', ['el punto penal', 'el centro del círculo', 'la línea de meta del arquero siempre'], 'Ocurre cuando el defensor manda el balón por su línea de fondo.'],
  ['¿Un saque de banda se hace…?', 'con las dos manos por encima de la cabeza', ['con el pie como un tiro libre', 'con el pecho', 'con un bate'], 'Los pies deben estar fuera o sobre la línea.'],
  ['¿La FIFA organiza sobre todo…?', 'el fútbol a nivel mundial', ['la NBA', 'el Tour de Francia', 'Wimbledon'], 'Dirige las Copas del Mundo.'],
  ['¿Cada cuántos años se juega el Mundial de fútbol?', '4', ['2', '1', '8'], 'El ciclo es el mismo que el olímpico de verano, en años distintos.'],
  ['¿Cada cuántos años se celebran los Juegos Olímpicos de verano?', '4', ['2', '3', '6'], 'El ciclo olímpico moderno es cuatrienal.'],
  ['¿Cuántos jugadores hay por equipo en la cancha de voleibol indoor?', '6', ['5', '7', '11'], 'Se juega 6 contra 6.'],
  ['¿El baloncesto se juega encestando en…?', 'un aro con tablero', ['una portería de 7,32 m', 'una red de tenis', 'un hoyo de golf'], 'La canasta vale 1, 2 o 3 puntos.'],
  ['¿Un triple en básquet se lanza…?', 'desde detrás de la línea de tres', ['desde debajo del aro solamente', 'desde el saque de banda de fútbol', 'desde el punto penal'], 'En FIBA la línea está a 6,75 m.'],
  ['¿Cuántos cuartos tiene un partido de básquet FIBA?', '4', ['2', '3', '5'], 'En FIBA duran 10 minutos cada uno.'],
  ['¿Michael Jordan destacó en…?', 'baloncesto', ['tenis', 'fútbol', 'atletismo de 100 m'], 'Jugó sobre todo en los Chicago Bulls.'],
  ['¿Pelé es una leyenda de…?', 'fútbol', ['boxeo', 'ciclismo', 'natación'], 'Ganó tres Mundiales con Brasil.'],
  ['¿Usain Bolt fue plusmarquista de…?', '100 y 200 metros', ['maratón', 'salto con pértiga', 'lanzamiento de bala'], 'Es el hombre más rápido en esas pruebas de velocidad.'],
  ['¿Simone Biles es una estrella de…?', 'gimnasia artística', ['clavados', 'vela', 'halterofilia'], 'Ha ganado múltiples oros olímpicos y mundiales.'],
  ['¿Un maratón olímpico mide…?', '42,195 km', ['21,097 km', '10 km', '50 km'], 'La distancia se fijó en Londres 1908 y se confirmó después.'],
  ['¿El Tour de Francia es una carrera de…?', 'ciclismo de ruta', ['atletismo', 'motociclismo', 'remo'], 'Se corre por etapas en julio.'],
  ['¿Wimbledon se juega sobre…?', 'césped', ['arcilla', 'pista dura', 'moqueta indoor exclusivamente'], 'Es el Grand Slam sobre hierba.'],
  ['¿Cuántos torneos de Grand Slam hay en el tenis anual?', '4', ['2', '3', '5'], 'Australia, Roland Garros, Wimbledon y US Open.'],
  ['¿Un ace en tenis es…?', 'un saque ganador que el rival no toca', ['un globo defensivo', 'un drop shot', 'una dejada de revés'], 'Suma el punto de inmediato.'],
  ['¿El circuito masculino de tenis se llama…?', 'ATP', ['FIFA', 'FIBA', 'UCI'], 'La WTA es el circuito femenino.'],
  ['¿Nairo Quintana y Egan Bernal destacan en…?', 'ciclismo', ['fútbol', 'boxeo', 'natación'], 'Ambos han ganado Grandes Vueltas.'],
  ['¿Egan Bernal ganó el Tour de Francia en…?', '2019', ['2012', '2006', '2024'], 'Fue el primer latinoamericano en lograrlo.'],
  ['¿Mariana Pajón fue campeona olímpica de…?', 'BMX', ['atletismo', 'judo', 'esgrima'], 'Ganó oros en Londres 2012 y Río 2016.'],
  ['¿Caterine Ibargüen ganó oro olímpico en…?', 'triple salto', ['100 metros', 'maratón', 'salto con pértiga'], 'Es una de las mejores saltadoras de la historia.'],
  ['¿Falcao García y James Rodríguez son figuras de…?', 'fútbol', ['ciclismo', 'béisbol', 'tenis'], 'Han sido referentes de la selección Colombia.'],
  ['¿Juan Pablo Montoya compitió al más alto nivel en…?', 'automovilismo', ['halterofilia', 'boxeo', 'atletismo'], 'Corrió Fórmula 1, IndyCar y NASCAR.'],
  ['¿Óscar Figueroa ganó oro olímpico en…?', 'halterofilia', ['boxeo', 'ciclismo', 'natación'], 'Lo logró en Río 2016.'],
  ['¿El tejo, deporte tradicional colombiano, consiste en…?', 'lanzar un disco hacia una mecha de pólvora', ['correr 42 km', 'encestar en un aro', 'patear un penal'], 'Es deporte nacional de Colombia.'],
  ['¿El coleo es un deporte típico de…?', 'los Llanos', ['el altiplano cundiboyacense', 'San Andrés', 'el Pacífico sur'], 'Los jinetes derriban el ganado en un manga.'],
  ['¿Un hat-trick en fútbol es…?', 'tres goles del mismo jugador', ['tres asistencias solamente', 'tres tarjetas', 'tres penales atajados solamente'], 'Es una tripleta en el mismo partido.'],
  ['¿El VAR en fútbol sirve para…?', 'revisar jugadas dudosas en video', ['cambiar al arquero sin aviso', 'medir la velocidad de un saque', 'sustituir el fuera de juego por completo'], 'Significa Video Assistant Referee.'],
  ['¿La Champions League es…?', 'la copa europea de clubes más prestigiosa', ['el Mundial de selecciones', 'la liga colombiana', 'un Grand Slam de tenis'], 'La juegan los mejores clubes de Europa.'],
  ['¿La Copa América enfrenta a…?', 'selecciones de América, sobre todo CONMEBOL', ['clubes de la NBA', 'ciclistas del Tour', 'tenistas de Wimbledon'], 'Es el torneo de selecciones más antiguo del mundo.'],
  ['¿Un touchdown es la anotación principal de…?', 'fútbol americano', ['fútbol asociativo', 'rugby a 15 exclusivamente en esta pregunta', 'béisbol'], 'Vale 6 puntos antes del extra.'],
  ['¿Un jonrón en béisbol es…?', 'un batazo que permite recorrer las cuatro bases', ['un penal', 'un ace', 'un try'], 'El bateador y los corredores anotan.'],
  ['¿El hockey sobre hielo se juega con…?', 'un disco o puck', ['un balón número 5', 'una pelota de tenis', 'una flecha'], 'Los patines se deslizan sobre la pista.'],
  ['¿El rugby se juega con un balón…?', 'ovalado', ['esférico de fútbol', 'de golf', 'de billar'], 'Se puede pasar hacia atrás con la mano.'],
  ['¿El boxeo se disputa en…?', 'un ring, con asaltos o rounds', ['una piscina', 'una cancha de 11', 'un velódromo'], 'Se usan guantes y un árbitro.'],
  ['¿Un knockout deja al rival…?', 'sin poder continuar el combate', ['con un saque de banda', 'con un time-out de básquet', 'con un córner'], 'El árbitro cuenta hasta diez o detiene el combate.'],
  ['¿El crol es…?', 'el estilo de natación más rápido', ['un golpe de boxeo', 'un paso de tango', 'un salto de esquí'], 'También se llama estilo libre.'],
  ['¿La braza y la mariposa son…?', 'estilos de natación', ['golpes de tenis', 'pruebas de atletismo de pista', 'posiciones de ajedrez'], 'Cada una tiene un reglamento de brazos y piernas.'],
  ['¿El salto con pértiga pertenece al…?', 'atletismo', ['tenis', 'boxeo', 'remo'], 'El atleta usa una vara para superar el listón.'],
  ['¿La jabalina, el disco y el peso son pruebas de…?', 'lanzamiento en atletismo', ['natación', 'gimnasia rítmica', 'esgrima'], 'Se miden por la distancia alcanzada.'],
  ['¿Los 100 metros lisos son una prueba de…?', 'velocidad', ['fondo de 42 km', 'medio fondo de 1500 m solamente', 'marcha atlética'], 'Se corre en recta de pista.'],
  ['¿Una carrera de relevos se corre…?', 'por equipos, pasando un testigo', ['en solitario contra el reloj solamente', 'en bicicleta de ruta', 'dentro de una piscina de clavados'], 'El 4x100 es el más famoso.'],
  ['¿El triatlón olímpico combina, en este orden…?', 'natación, ciclismo y carrera a pie', ['boxeo, salto y remo', 'tenis, golf y ajedrez', 'fútbol, básquet y voley'], 'No se cambia el orden olímpico.'],
  ['¿El taekwondo es un arte marcial de origen…?', 'coreano', ['brasileño', 'japonés exclusivo del judo', 'griego de la lucha antigua'], 'Destaca por las patadas y es olímpico.'],
  ['¿El judo se caracteriza por…?', 'proyecciones y control en el suelo', ['patadas altas de taekwondo solamente', 'esgrima con sable', 'nado sincronizado'], 'El objetivo es derribar o inmovilizar.'],
  ['¿La esgrima se disputa con…?', 'espada, florete o sable', ['un balón ovalado', 'un disco de hielo', 'una raqueta'], 'Es uno de los deportes olímpicos más antiguos.'],
  ['¿La Fórmula 1 es la máxima categoría del…?', 'automovilismo en circuitos', ['motociclismo de motocross', 'rally exclusivo de tierra', 'karting infantil'], 'Los monoplazas corren un campeonato mundial.'],
  ['¿MotoGP es el mundial de…?', 'motociclismo de velocidad', ['ciclismo de pista', 'remo', 'tiro con arco'], 'Las motos alcanzan más de 300 km/h.'],
  ['¿El waterpolo se juega…?', 'en una piscina, con porterías', ['en una cancha de arcilla', 'sobre hielo', 'en un velódromo'], 'Combina nado, pase y lanzamiento.'],
  ['¿El remo se practica en…?', 'botes impulsados con remos', ['motos de agua', 'caballos de salto', 'monopatines'], 'Hay embarcaciones de 1, 2, 4 u 8 remeros.'],
  ['¿El surf se practica…?', 'sobre las olas, con una tabla', ['sobre hielo con un disco', 'en una pista de tartán', 'en un ring'], 'El deportista se incorpora sobre la tabla.'],
  ['¿El esquí alpino se practica sobre…?', 'nieve', ['césped de fútbol', 'arena de playa', 'piso de parquet de básquet'], 'Se usan dos tablas y bastones.'],
  ['¿El curling se juega deslizando…?', 'piedras de granito sobre hielo', ['un puck de hockey', 'un balón de fútbol', 'una jabalina'], 'Los barrenderos guían la trayectoria.'],
  ['¿El ajedrez se considera…?', 'un juego de estrategia con 64 casillas', ['un deporte de contacto', 'una carrera de 100 m', 'un salto ornamental'], 'Cada bando tiene 16 piezas.'],
  ['¿La NBA es la liga principal de…?', 'baloncesto en Estados Unidos', ['fútbol europeo', 'béisbol japonés', 'críquet inglés'], 'Tiene 30 franquicias.'],
  ['¿Un rebote en básquet es…?', 'atrapar el balón tras un tiro que no entra', ['un saque de banda', 'un ace', 'un fuera de lugar'], 'Puede ser ofensivo o defensivo.'],
  ['¿Driblear en básquet es…?', 'avanzar botando el balón', ['nadar crol', 'lanzar jabalina', 'saltar vallas'], 'Sin bote, hay pasos en falso.'],
  ['¿La valla invicta de un arquero significa…?', 'que no le anotaron goles', ['que no sacó córners', 'que no tocó el balón', 'que fue expulsado'], 'Se dice que “dejó el arco en cero”.'],
  ['¿Un autogol es…?', 'un tanto en la propia portería', ['un triple en aro propio', 'un ace del compañero', 'un try anulado'], 'Suma para el equipo rival.'],
  ['¿La prórroga en fútbol se juega cuando…?', 'hay empate y el reglamento pide un ganador', ['empieza el partido', 'hay un saque de meta', 'el arquero pide agua'], 'Suelen ser dos tiempos de 15 minutos.'],
  ['¿Los penales decisivos se patean para…?', 'desempatar al final de algunos partidos', ['empezar el segundo tiempo', 'cobrar todos los córners', 'cambiar de arquero'], 'Cada equipo lanza una serie desde los 11 m.'],
  ['¿El patinaje de carreras ha dado a Colombia…?', 'múltiples títulos mundiales', ['oros de Wimbledon', 'anillos de la Super Bowl', 'copas Davis'], 'Es una de las potencias mundiales del patinaje.'],
  ['¿Una contrarreloj ciclista se corre…?', 'contra el reloj, de uno en uno o por equipos', ['en un velódromo de persecución solamente', 'en una piscina', 'en un ring'], 'Gana quien hace el menor tiempo.'],
  ['¿El Giro de Italia y la Vuelta a España son, como el Tour…?', 'Grandes Vueltas de ciclismo', ['slams de tenis', 'mundiales de atletismo', 'copas de rugby'], 'Cada una dura tres semanas.'],
];

module.exports = {
  MEDIUM_SCIENCE,
  MEDIUM_CULTURE,
  MEDIUM_ART,
  MEDIUM_SPORTS,
};
