const EXTRA_HISTORY_EVENTS = [
  ['Independencia de Argentina', '1816', 'América del Sur', 'el Congreso de Tucumán'],
  ['Independencia de Chile', '1818', 'América del Sur', 'la batalla de Maipú'],
  ['Independencia de Perú', '1821', 'América del Sur', 'la proclamación de San Martín'],
  ['Grito de Independencia de Ecuador', '1809', 'Quito', 'uno de los primeros gritos andinos'],
  ['Revolución de los Comuneros', '1781', 'Colombia', 'la protesta contra impuestos coloniales'],
  ['Fundación de Cartagena', '1533', 'Colombia', 'Pedro de Heredia'],
  ['Sitio de Cartagena', '1741', 'Colombia', 'la defensa frente a Blas de Lezo'],
  ['Conquista de Tenochtitlán', '1521', 'México', 'la caída del Imperio azteca'],
  ['Caída del Imperio inca', '1533', 'Perú', 'la captura de Atahualpa'],
  ['Revolución haitiana', '1791', 'Haití', 'el levantamiento liderado por esclavos'],
  ['Declaración de Independencia de EE. UU.', '1776', 'América del Norte', 'el 4 de julio'],
  ['Revolución china', '1949', 'China', 'la proclamación de la República Popular'],
  ['Independencia de la India', '1947', 'Asia', 'el fin del dominio británico'],
  ['Apertura del Canal de Panamá', '1914', 'Panamá', 'la conexión entre dos océanos'],
  ['Conferencia de Bandung', '1955', 'Asia', 'el movimiento de países no alineados'],
  ['Crisis de los misiles', '1962', 'Cuba', 'la tensión nuclear entre EE. UU. y la URSS'],
  ['Fin del apartheid', '1994', 'Sudáfrica', 'la elección de Nelson Mandela'],
  ['Creación de la Unión Europea', '1993', 'Europa', 'el Tratado de Maastricht'],
  ['Invención de Internet público', 'años 1990', 'el mundo', 'la World Wide Web'],
  ['Primer vuelo de los hermanos Wright', '1903', 'Estados Unidos', 'el inicio de la aviación'],
  ['Viaje de Magallanes', '1519', 'el mundo', 'la primera circunnavegación'],
  ['Caída de Constantinopla', '1453', 'Turquía', 'el fin del Imperio bizantino'],
  ['Reforma protestante', '1517', 'Alemania', 'las 95 tesis de Lutero'],
  ['Ilustración', 'siglo XVIII', 'Europa', 'la era de la razón y los derechos'],
  ['Guerra de los Mil Días', '1899', 'Colombia', 'un conflicto civil de inicios del siglo XX'],
  ['Frente Nacional', '1958', 'Colombia', 'el pacto entre liberales y conservadores'],
  ['Constitución de Cúcuta', '1821', 'Gran Colombia', 'la carta de la Gran Colombia'],
  ['Batalla de Carabobo', '1821', 'Venezuela', 'una victoria de Bolívar'],
  ['Batalla de Ayacucho', '1824', 'Perú', 'el fin del dominio español en Sudamérica'],
  ['Congreso de Panamá', '1826', 'Panamá', 'el proyecto de unión de Bolívar'],
];

const EXTRA_SCIENCE = [
  ['páramo', 'ecosistema de alta montaña', ['un desierto caliente', 'un arrecife', 'una selva tropical baja'], 'El páramo es un ecosistema de montaña húmedo y frío.'],
  ['Amazonas', 'la selva tropical más grande', ['un desierto africano', 'un glaciar europeo', 'una isla volcánica'], 'El Amazonas es la selva tropical más extensa del planeta.'],
  ['Andes', 'la cordillera más larga de América', ['un río de África', 'un desierto de Asia', 'un archipiélago'], 'Los Andes recorren el oeste de América del Sur.'],
  ['Pacífico', 'el océano más grande', ['el Atlántico', 'el Índico', 'el Ártico'], 'El Pacífico es el océano de mayor superficie.'],
  ['Atlántico', 'océano entre América y Europa', ['el Pacífico', 'el Índico', 'el Ártico'], 'El Atlántico separa América de Europa y África.'],
  ['evaporación', 'el agua pasa a vapor', ['el agua se congela', 'la roca se parte', 'el hierro se oxida'], 'En la evaporación el agua líquida se vuelve gas.'],
  ['condensación', 'el vapor se vuelve líquido', ['el hielo se derrite', 'la madera se quema', 'el imán atrae'], 'La condensación forma gotas a partir del vapor.'],
  ['ciclo del agua', 'evaporación, condensación y precipitación', ['solo terremotos', 'solo eclipses', 'solo mareas de lava'], 'El ciclo del agua mueve el agua entre tierra, aire y océanos.'],
  ['suelo fértil', 'tiene nutrientes para plantas', ['es solo cemento', 'es solo vidrio', 'es solo plástico'], 'Un suelo fértil permite que crezcan cultivos.'],
  ['semilla', 'da origen a una nueva planta', ['es un mineral', 'es un gas', 'es un metal'], 'La semilla contiene el embrión de la planta.'],
  ['raíz', 'absorbe agua y sujeta la planta', ['hace la fotosíntesis', 'canta', 'vuela'], 'La raíz ancla la planta y toma agua del suelo.'],
  ['hoja', 'hace gran parte de la fotosíntesis', ['bombea sangre', 'produce lava', 'mide el tiempo'], 'Las hojas captan luz para fabricar alimento.'],
  ['flor', 'parte reproductiva de muchas plantas', ['un hueso', 'un planeta', 'un deporte'], 'La flor permite la reproducción de muchas plantas.'],
  ['fruto', 'protege las semillas', ['es un metal', 'es un gas noble', 'es un fósil lunar'], 'El fruto rodea y protege las semillas.'],
  ['hongo', 'no hace fotosíntesis como las plantas', ['es un mamífero', 'es un planeta', 'es un metal'], 'Los hongos se alimentan de materia orgánica.'],
  ['mamífero', 'amamanta a sus crías', ['pone siempre huevos de piedra', 'no tiene columna', 'respira solo por branquias'], 'Los mamíferos alimentan a sus crías con leche.'],
  ['ave', 'tiene plumas y pone huevos', ['tiene escamas de pez', 'amamanta siempre', 'vive solo en el núcleo terrestre'], 'Las aves tienen plumas y la mayoría vuela.'],
  ['reptil', 'tiene escamas y es de sangre fría', ['tiene plumas', 'amamanta', 'es un hongo'], 'Los reptiles son vertebrados de sangre fría con escamas.'],
  ['anfibio', 'vive en agua y tierra', ['vive solo en el espacio', 'es un mineral', 'es un deporte'], 'Los anfibios suelen nacer en el agua y luego vivir en tierra.'],
  ['pez', 'respira por branquias', ['respira con pulmones de ave', 'tiene plumas', 'pone semillas'], 'Los peces toman oxígeno del agua con las branquias.'],
  ['columna vertebral', 'sostén óseo del cuerpo', ['un músculo de la mano', 'un gas', 'una vitamina'], 'La columna protege la médula y sostiene el tronco.'],
  ['músculo', 'permite el movimiento', ['transporta solo luz', 'almacena solo oro', 'produce solo viento'], 'Los músculos se contraen para movernos.'],
  ['esqueleto', 'da forma y protege órganos', ['digiere alimentos', 've colores', 'escucha sonidos'], 'El esqueleto sostiene el cuerpo y protege órganos.'],
  ['articulación', 'une dos huesos', ['une dos océanos', 'une dos planetas', 'une dos idiomas'], 'Las articulaciones permiten doblar brazos y piernas.'],
  ['sistema digestivo', 'transforma los alimentos', ['bombea solo aire a Marte', 'pinta paredes', 'mide terremotos'], 'El sistema digestivo obtiene nutrientes de la comida.'],
  ['sistema respiratorio', 'intercambia oxígeno y CO2', ['cose tela', 'fabrica imanes', 'cuenta goles'], 'Respiramos para tomar oxígeno y expulsar dióxido de carbono.'],
  ['sistema circulatorio', 'transporta sangre', ['transporta solo libros', 'transporta solo lava', 'transporta solo nieve'], 'La sangre lleva oxígeno y nutrientes por el cuerpo.'],
  ['neurona', 'célula del sistema nervioso', ['una célula de la madera', 'un tipo de nube', 'un planeta enano'], 'Las neuronas transmiten señales eléctricas.'],
  ['reflejo', 'respuesta automática del cuerpo', ['un tipo de receta', 'un deporte de raqueta', 'un estilo de pintura'], 'Un reflejo ocurre sin pensarlo, como retirar la mano del fuego.'],
  ['vacuna de refuerzo', 'mantiene la protección', ['borra la memoria', 'cambia el color de ojos', 'detiene la lluvia'], 'Algunas vacunas necesitan dosis de refuerzo.'],
  ['antibiótico', 'trata algunas infecciones bacterianas', ['cura todos los virus', 'pinta metales', 'enfría el Sol'], 'Los antibióticos no sirven contra todos los virus.'],
  ['virus', 'necesita una célula para reproducirse', ['es un mamífero', 'es un metal', 'es un continente'], 'Los virus infectan células para multiplicarse.'],
  ['sistema inmune', 'defiende el cuerpo', ['solo pinta la piel', 'solo mide el viento', 'solo produce eco'], 'El sistema inmune combate gérmenes.'],
  ['órbita elíptica', 'forma de las órbitas planetarias', ['un cubo perfecto', 'una línea recta fija', 'un triángulo'], 'Los planetas siguen órbitas elípticas alrededor del Sol.'],
  ['año terrestre', 'una vuelta de la Tierra al Sol', ['una vuelta de la Luna', 'un día solar', 'un eclipse'], 'Un año es el tiempo que tarda la Tierra en orbitar al Sol.'],
  ['día', 'una rotación de la Tierra', ['una órbita al Sol', 'un mes lunar', 'una era geológica'], 'El día dura porque la Tierra gira sobre su eje.'],
  ['estaciones', 'inclinación del eje terrestre', ['el color del océano', 'el peso de la Luna', 'el sonido del viento'], 'Las estaciones ocurren por la inclinación del eje de la Tierra.'],
  ['solsticio', 'el día más largo o más corto', ['un tipo de pez', 'un metal', 'un deporte'], 'Los solsticios marcan verano e invierno.'],
  ['equinoccio', 'día y noche casi iguales', ['un volcán', 'un hueso', 'un río'], 'En los equinoccios el día y la noche duran casi lo mismo.'],
  ['magnitud de un sismo', 'mide su energía', ['mide el color del cielo', 'mide la edad de un árbol', 'mide un gol'], 'La magnitud indica qué tan fuerte fue el terremoto.'],
  ['epicentro', 'punto superficial sobre el sismo', ['el núcleo del Sol', 'una nube', 'un cometa'], 'El epicentro está en la superficie, sobre el origen del sismo.'],
  ['placa tectónica', 'bloque de la corteza terrestre', ['un tipo de ave', 'un gas noble', 'un estilo de danza'], 'Las placas se mueven y pueden causar sismos.'],
  ['fósil de amonite', 'resto de un animal marino antiguo', ['una moneda de hoy', 'un celular', 'un avión'], 'Los amonites vivieron en mares del pasado.'],
  ['era de los dinosaurios', 'Mesozoico', ['Cenozoico solo humano', 'la Edad Media', 'el siglo XX'], 'Los dinosaurios dominaron durante el Mesozoico.'],
  ['extinción de dinosaurios no avianos', 'hace unos 66 millones de años', ['hace 100 años', 'hace 1000 años', 'en 1492'], 'Un impacto y cambios climáticos marcaron su extinción.'],
  ['energía cinética', 'energía del movimiento', ['energía de estar quieto', 'solo color', 'solo sabor'], 'Un objeto en movimiento tiene energía cinética.'],
  ['energía potencial', 'energía guardada por posición', ['solo sonido', 'solo olor', 'solo eco'], 'Un objeto en lo alto tiene energía potencial gravitatoria.'],
  ['fricción', 'fuerza que se opone al deslizamiento', ['una vitamina', 'un planeta', 'un idioma'], 'La fricción frena o calienta al frotar superficies.'],
  ['presión', 'fuerza sobre un área', ['un color primario', 'un estilo musical', 'un hueso'], 'La presión es mayor si la misma fuerza actúa en menos área.'],
  ['densidad', 'masa entre volumen', ['color entre tiempo', 'sonido entre peso', 'luz entre eco'], 'Un objeto denso tiene mucha masa en poco espacio.'],
  ['flotación', 'el empuje del fluido', ['el color verde', 'el eco', 'el sabor dulce'], 'Un objeto flota si el empuje del agua iguala su peso.'],
  ['punto de fusión', 'cuando un sólido se vuelve líquido', ['cuando un gas se vuelve planeta', 'cuando un sonido se ve', 'cuando un color pesa'], 'El hielo funde al pasar a agua líquida.'],
  ['sublimación', 'de sólido a gas', ['de líquido a sólido siempre', 'de gas a metal', 'de luz a piedra'], 'El hielo seco pasa de sólido a gas por sublimación.'],
  ['mezcla', 'se puede separar por medios físicos', ['siempre es un elemento puro', 'siempre es un planeta', 'siempre es un deporte'], 'El agua con arena es una mezcla separable.'],
  ['compuesto', 'átomos de distintos elementos unidos', ['un solo electrón suelto', 'una galaxia', 'un estadio'], 'El agua es un compuesto de hidrógeno y oxígeno.'],
  ['tabla periódica', 'organiza los elementos', ['organiza países', 'organiza deportes', 'organiza recetas'], 'Mendeleiev ordenó los elementos en la tabla periódica.'],
  ['reacción química', 'cambia la sustancia', ['solo cambia el color del cielo', 'solo mueve un balón', 'solo pinta un muro'], 'En una reacción se forman sustancias nuevas.'],
  ['oxidación del hierro', 'el hierro se oxida con oxígeno y humedad', ['el hierro se vuelve gas noble', 'el hierro se vuelve planta', 'el hierro se vuelve nube'], 'El óxido aparece cuando el hierro reacciona con el aire húmedo.'],
  ['combustión', 'reacción con oxígeno que suelta energía', ['una danza', 'un río', 'un fósil'], 'La combustión produce calor y a menudo luz.'],
  ['cadena de carbono', 'base de la química orgánica', ['base del fútbol', 'base de un puente solo', 'base de un volcán'], 'Los compuestos orgánicos contienen carbono.'],
  ['pH ácido', 'menor que 7', ['igual a 14 siempre', 'igual a 7', 'mayor que 20'], 'El limón es ácido: su pH es menor que 7.'],
  ['pH básico', 'mayor que 7', ['igual a 0 siempre', 'igual a 7', 'menor que -10'], 'El jabón suele ser básico, con pH mayor que 7.'],
  ['capa de ozono', 'protege de rayos UV', ['produce petróleo', 'enfría el núcleo', 'crea terremotos'], 'El ozono en la estratosfera filtra radiación ultravioleta.'],
  ['efecto invernadero', 'retiene calor en la atmósfera', ['apaga el Sol', 'congela el núcleo', 'borra nubes'], 'Algunos gases retienen calor y calientan el planeta.'],
  ['biodiversidad', 'variedad de seres vivos', ['un solo tipo de roca', 'un único idioma', 'un único color'], 'Más biodiversidad hace más fuerte un ecosistema.'],
  ['especie en peligro', 'puede extinguirse', ['es un planeta nuevo', 'es un metal líquido', 'es un deporte'], 'Si una especie está en peligro, quedan pocos individuos.'],
  ['hábitat', 'lugar donde vive una especie', ['un tipo de gol', 'un instrumento', 'un número primo'], 'El hábitat da alimento, refugio y condiciones de vida.'],
  ['migración animal', 'viaje periódico de animales', ['un eclipse', 'una receta', 'un puente'], 'Muchas aves migran según las estaciones.'],
  ['cadena trófica marina', 'fitoplancton en la base', ['solo tiburones sin alimento', 'solo plásticos', 'solo volcanes'], 'El fitoplancton alimenta gran parte del océano.'],
  ['coral', 'animal que forma arrecifes', ['una planta de desierto', 'un metal', 'una nube'], 'Los corales son animales que construyen arrecifes.'],
  ['plancton', 'seres diminutos del agua', ['montañas', 'rascacielos', 'desiertos'], 'El plancton flota y es alimento de muchos animales.'],
  ['ballena', 'mamífero marino', ['un pez con escamas de oro', 'un reptil volador', 'un insecto'], 'Las ballenas respiran aire y amamantan.'],
  ['murciélago', 'mamífero volador', ['un ave sin pelo', 'un pez', 'un anfibio'], 'Los murciélagos son los únicos mamíferos que vuelan de verdad.'],
  ['canguros', 'marsupiales de Australia', ['aves de África', 'peces del Ártico', 'reptiles de Europa'], 'Las crías de canguro se crían en la bolsa marsupial.'],
  ['cóndor de los Andes', 'ave carroñera de montaña', ['un pez de río', 'un insecto', 'un hongo'], 'El cóndor andino es un símbolo de los Andes.'],
];

const EXTRA_CULTURE = [
  ['ajiaco', 'sopa típica de Bogotá', ['un baile japonés', 'un río de África', 'un planeta']],
  ['bandeja paisa', 'plato típico antioqueño', ['un soneto', 'un volcán', 'un satélite']],
  ['sancocho', 'sopa espesa latinoamericana', ['un estilo de pintura cubista', 'un motor', 'un cometa']],
  ['ajiaco santafereño', 'lleva papa, mazorca y pollo', ['lleva solo hielo', 'lleva solo café', 'lleva solo mango']],
  ['tamal', 'masa envuelta en hoja', ['un instrumento de viento', 'un deporte de hielo', 'un gas']],
  ['empanada colombiana', 'masa frita rellena', ['una sonata', 'un glaciar', 'un eclipse']],
  ['natilla y buñuelos', 'típicos de Navidad en Colombia', ['típicos del Mundial de ajedrez', 'típicos de un eclipse', 'típicos de un sismo']],
  ['champús', 'bebida de lulo o piña', ['un estilo de boxeo', 'un tipo de raqueta', 'un hueso']],
  ['chicha', 'bebida fermentada ancestral', ['un satélite', 'un penal', 'un fósil lunar']],
  ['sombrero aguadeño', 'sombrero de Aguadas', ['un casco de F1', 'un aro de básquet', 'un remo']],
  ['mochila arhuaca', 'artesanía de la Sierra Nevada', ['un motor de avión', 'un telescopio', 'un estadio']],
  ['mochila wayuu', 'tejido de La Guajira', ['un puente romano', 'un volcán islandés', 'un glaciar']],
  ['ruana', 'prenda andina de lana', ['un tipo de gol', 'un planeta', 'un antibiótico']],
  ['alpargatas', 'calzado tradicional', ['un instrumento de percusión-metal', 'un cometa', 'un virus']],
  ['feria de Cali', 'fiesta vallecaucana', ['un tratado medieval', 'un elemento químico', 'un cráter lunar']],
  ['carnaval de Negros y Blancos', 'Pasto', ['Tunja', 'Leticia', 'Yopal']],
  ['festival vallenato', 'Valledupar', ['Manizales', 'Ipiales', 'Turbo']],
  ['rock al parque', 'festival en Bogotá', ['una receta de sopa', 'un hueso del pie', 'un gas noble']],
  ['teatro Colón de Bogotá', 'sala histórica de artes', ['un velódromo', 'una refinería', 'un faro']],
  ['ciudad amurallada', 'Cartagena', ['Sogamoso', 'Zipaquirá', 'Girardot']],
  ['Catedral de Sal', 'Zipaquirá', ['Apartadó', 'Turbo', 'La Dorada']],
  ['Santuario de Las Lajas', 'Nariño', ['La Guajira', 'San Andrés', 'el Chocó costero']],
  ['Parque Tayrona', 'el Magdalena', ['el Eje Cafetero central', 'el desierto de la Tatacoa solo', 'la Patagonia']],
  ['Caño Cristales', 'río de colores en la Macarena', ['un volcán de Islandia', 'un desierto de Chile', 'un fiordo noruego']],
  ['Desierto de la Tatacoa', 'Huila', ['Boyacá', 'San Andrés', 'el Amazonas peruano']],
  ['Sierra Nevada de Santa Marta', 'la costa Caribe', ['los Alpes', 'los Pirineos', 'el Atlas']],
  ['islas de San Andrés', 'el Caribe colombiano', ['el Pacífico chileno', 'el Mediterráneo', 'el Mar Negro']],
  ['Leticia', 'capital del Amazonas colombiano', ['capital de Boyacá', 'capital de Caldas', 'capital de Quindío']],
  ['idioma embera', 'lengua indígena de Colombia', ['un dialecto del japonés antiguo', 'un idioma de Islandia', 'un código de F1']],
  ['mitología muisca', 'Bachué y el agua', ['Odín y el trueno nórdico', 'Zeus solamente griego', 'Anubis egipcio']],
  ['El Dorado muisca', 'ofrendas en lagunas', ['una receta de pan', 'un gol olímpico', 'un cometa']],
  ['laguna de Guatavita', 'asociada a El Dorado', ['asociada al Tour de Francia', 'asociada a la NBA', 'asociada al Nobel de Física']],
  ['día de las velitas', 'tradición mariana de diciembre', ['un mundial de rugby', 'un eclipse solar', 'un solsticio chino']],
  ['novena de aguinaldos', 'tradición navideña colombiana', ['un reglamento de básquet', 'una tabla periódica', 'un mapa estelar']],
  ['día de los muertos en México', 'honra a los antepasados', ['celebra solo un mundial', 'celebra solo un eclipse', 'celebra solo un sismo']],
  ['intirraymi', 'fiesta inca del Sol', ['un estilo de natación', 'un tipo de penal', 'un gas']],
  ['samba', 'danza y música de Brasil', ['un río de Siberia', 'un hueso', 'un satélite']],
  ['tango', 'música de Argentina y Uruguay', ['un volcán de Japón', 'un desierto de Namibia', 'un fiordo']],
  ['flamenco', 'arte de Andalucía', ['un deporte de hielo', 'un motor', 'un cometa']],
  ['haiku', 'poema breve japonés', ['un gol de tijera', 'un antibiótico', 'un cráter']],
  ['ópera', 'teatro cantado', ['un estilo de boxeo', 'un tipo de remo', 'un fósil']],
  ['UNESCO', 'protege patrimonios culturales', ['organiza solo la NBA', 'fabrica autos', 'árbitra penales']],
  ['idioma oficial de Brasil', 'portugués', ['español', 'francés', 'italiano']],
  ['idioma oficial de Haití', 'criollo haitiano y francés', ['solo quechua', 'solo swahili', 'solo japonés']],
  ['comida peruana emblemática', 'el ceviche', ['el pretzel', 'el sushi de Hokkaido', 'el kimchi coreano']],
  ['arepas venezolanas y colombianas', 'masa de maíz', ['masa de centeno nórdico', 'pasta de arroz japonés', 'trigo de baguette']],
  ['mate', 'infusión del Cono Sur', ['un estilo de judo', 'un planeta', 'un virus']],
  ['Día de la Raza o de la Diversidad', '12 de octubre', ['1 de mayo', '25 de diciembre', '31 de octubre']],
  ['himno nacional', 'canción oficial de un país', ['un tipo de córner', 'un gas noble', 'un hueso']],
  ['bandera', 'símbolo oficial de un país', ['un estilo de natación', 'un motor', 'un cometa']],
];

const EXTRA_ART = [
  ['colores secundarios', 'verde, naranja y morado', ['rojo, azul y amarillo', 'blanco y negro', 'dorado y plata']],
  ['complementarios', 'colores opuestos en el círculo', ['colores que no existen', 'solo blancos', 'solo metales']],
  ['círculo cromático', 'organiza los colores', ['organiza países', 'organiza ligas', 'organiza átomos']],
  ['clarooscuro', 'contraste de luz y sombra', ['un ritmo de salsa', 'un tipo de gol', 'un gas']],
  ['composición', 'organización de una obra', ['un saque de banda', 'un pH', 'un sismo']],
  ['simetría', 'equilibrio de formas', ['un estilo de boxeo', 'un océano', 'un virus']],
  ['textura', 'calidad visual o táctil de una superficie', ['un planeta', 'un penal', 'un idioma']],
  ['volumen en dibujo', 'se sugiere con luz y sombra', ['se patea', 'se nada', 'se hornea']],
  ['boceto', 'dibujo preparatorio', ['un gol olímpico', 'un antibiótico', 'un fiordo']],
  ['fresco', 'pintura sobre muro húmedo', ['un estilo de surf', 'un motor', 'un cometa']],
  ['temple', 'pintura con yema o cola', ['un deporte de motor', 'un río', 'un satélite']],
  ['gouache', 'acuarela opaca', ['un tackle', 'un eclipse', 'un fósil']],
  ['pastel', 'barras de pigmento suave', ['un casco', 'un remo', 'un faro']],
  ['collage', 'pega recortes en una superficie', ['un 100 metros', 'un pH ácido', 'un cráter']],
  ['instalación artística', 'obra que ocupa un espacio', ['un córner', 'una vacuna', 'un glaciar']],
  ['performance', 'arte en vivo con el cuerpo', ['un putt', 'un solsticio', 'un metal']],
  ['videoarte', 'obra hecha con imagen en movimiento', ['un saque de honor', 'un hueso', 'un desierto']],
  ['diseño gráfico', 'comunica con imagen y texto', ['árbitra un penal', 'mide sismos', 'cosecha trigo']],
  ['tipografía', 'diseño de letras', ['un estilo de judo', 'un volcán', 'un pez']],
  ['fotograma', 'imagen fija de una película', ['un triple', 'un gas noble', 'un páramo']],
  ['cine', 'arte de contar con imágenes en movimiento', ['un tipo de remo', 'un antibiótico', 'un cometa']],
  ['guion', 'texto de una película o obra', ['un mapa de placas', 'una tabla de posiciones', 'un pH']],
  ['plano cinematográfico', 'encuadre de la cámara', ['un fuera de juego', 'un epicentro', 'un isótopo']],
  ['ópera bufa', 'ópera cómica', ['un rally', 'un sismo', 'un glaciar']],
  ['zarzuela', 'teatro musical español', ['un slalom', 'un cráter', 'un virus']],
  ['bambuco en escena', 'danza andina colombiana', ['un estilo de F1', 'un gas', 'un fósil lunar']],
  ['cumbia en el arte', 'música y baile del Caribe', ['un tipo de pértiga', 'un planeta enano', 'un imán']],
  ['mapalé', 'danza afrocolombiana', ['un saque de rugby', 'un solsticio', 'un metal líquido']],
  ['joropo', 'música de los Llanos', ['un 400 metros', 'un cometa', 'un antibiótico']],
  ['currulao', 'ritmo del Pacífico colombiano', ['un ace', 'un fiordo', 'un pH']],
  ['tiple colombiano', 'instrumento de 12 cuerdas', ['un bate', 'un casco de F1', 'un telescopio']],
  ['bandola andina', 'instrumento de cuerda', ['un disco de hockey', 'un remo', 'un faro']],
  ['gaita colombiana', 'instrumento de viento costeño', ['un aro de básquet', 'un putt', 'un sismo']],
  ['marimba del Pacífico', 'instrumento de láminas', ['un penalty', 'un volcán islandés', 'un satélite']],
  ['arpa llanera', 'cuerdas de los Llanos', ['un knock-out', 'un glaciar', 'un virus']],
  ['contrapunto', 'varias melodías a la vez', ['un córner', 'un epicentro', 'un isótopo']],
  ['armonía', 'combinación de acordes', ['un slalom', 'un desierto', 'un hueso']],
  ['compás musical', 'organización de tiempos', ['un triple', 'un pH', 'un cráter']],
  ['clave de sol', 'indica la altura de las notas', ['indica un penal', 'indica un sismo', 'indica un gol']],
  ['pentagrama', 'cinco líneas para escribir música', ['tres aros de básquet', 'un velódromo', 'una pista de hielo']],
  ['sonata', 'obra instrumental en varios movimientos', ['un 100 metros', 'una vacuna', 'un cometa']],
  ['concierto para solista', 'solista y orquesta', ['un 2 vs 2 de fútbol', 'un eclipse', 'un fósil']],
  ['ópera de Verdi', 'drama musical italiano', ['un rally', 'un páramo', 'un metal']],
  ['Beethoven', 'autor de la Quinta Sinfonía', ['Pelé', 'Newton', 'Messi']],
  ['Mozart', 'compositor del clasicismo', ['Usain Bolt', 'Einstein', 'Bolívar']],
  ['Bach', 'maestro del barroco musical', ['Michael Jordan', 'Darwin', 'Falcao']],
  ['Shakira', 'artista colombiana de música pop', ['una física nuclear del siglo XVII', 'una pintora flamenca del 1400', 'una reina egipcia']],
  ['Carlos Vives', 'música vallenata y pop', ['un ciclista belga del XIX', 'un químico ruso', 'un emperador romano']],
  ['Totó la Momposina', 'música folclórica del Caribe', ['una nadadora olímpica de los 50', 'una chef francesa', 'una piloto de F1']],
  ['Fernando Botero plaza', 'esculturas monumentales', ['solo grafitis diminutos', 'solo partituras', 'solo fotos de lunas']],
  ['murales de Pedro Nel Gómez', 'Medellín', ['Oslo', 'Kioto', 'El Cairo']],
  ['arte precolombino', 'orfebrería y cerámica antiguas', ['Fórmula 1', 'NBA', 'MotoGP']],
  ['orfebrería muisca', 'oro trabajado en ofrendas', ['hielo tallado', 'plástico industrial', 'concreto armado']],
  ['cerámica quimbaya', 'vasijas prehispánicas', ['cascos de F1', 'raquetas', 'remos']],
  ['arte rupestre de Chiribiquete', 'pinturas en la selva', ['neón de estadio', 'vallas de atletismo', 'aros de básquet']],
  ['pop art', 'usa imágenes de la cultura popular', ['solo fósiles', 'solo sismos', 'solo penales']],
  ['expresionismo', 'emoción intensa en la forma', ['un estilo de crol', 'un pH', 'un fiordo']],
  ['romanticismo artístico', 'emoción y naturaleza', ['un offside', 'un isótopo', 'un cráter']],
  ['neoclasicismo', 'vuelve a modelos grecolatinos', ['un slam dunk', 'un virus', 'un desierto']],
  ['art nouveau', 'líneas curvas y formas naturales', ['un tackle', 'un gas noble', 'un cometa']],
  ['bauhaus', 'une arte, oficio y diseño', ['un mundial de rugby', 'un solsticio', 'un hueso']],
  ['ready-made', 'objeto cotidiano convertido en arte', ['un 400 metros', 'una vacuna', 'un glaciar']],
];

const EXTRA_SPORTS = [
  ['Nairo Quintana', 'ciclismo', ['natación', 'esgrima', 'halterofilia']],
  ['Egan Bernal', 'ciclismo de ruta', ['boxeo', 'remo', 'clavados']],
  ['Mariana Pajón', 'BMX', ['vela', 'curling', 'polo']],
  ['Caterine Ibargüen', 'triple salto', ['waterpolo', 'luge', 'sumo']],
  ['Rigoberto Urán', 'ciclismo', ['tenis de mesa', 'golf', 'esquí']],
  ['Falcao García', 'fútbol', ['béisbol', 'hockey sobre hielo', 'bádminton']],
  ['James Rodríguez', 'fútbol', ['lucha', 'tiro con arco', 'escalada']],
  ['Yerry Mina', 'fútbol', ['patinaje de velocidad', 'bobsleigh', 'ráquetbol']],
  ['Juan Pablo Montoya', 'automovilismo', ['halterofilia', 'judo', 'taekwondo']],
  ['Óscar Figueroa', 'halterofilia', ['surf', 'skateboarding', 'escalada']],
  ['Yuberjen Martínez', 'boxeo', ['tenis', 'golf', 'críquet']],
  ['selección Colombia', 'fútbol', ['críquet test', 'lacrosse', 'hurling']],
  ['copa América', 'torneo de selecciones', ['un slam de tenis', 'un Tour de pista', 'un Ironman']],
  ['liga colombiana', 'fútbol profesional', ['NBA solamente', 'NHL solamente', 'MLB solamente']],
  ['clásico colombiano', 'Millonarios vs Santa Fe u otros rivales', ['Wimbledon vs Roland Garros', 'Tour vs Giro', 'NBA vs NHL']],
  ['saque de banda', 'se hace con las manos', ['se patea de tijera', 'se encesta', 'se nada']],
  ['córner', 'saque desde la esquina', ['un ace de tenis', 'un triple', 'un jonrón']],
  ['tiro libre en fútbol', 'falta cerca del área', ['un set de voleibol', 'un asalto de boxeo', 'un relevo']],
  ['tarjeta amarilla', 'amonestación', ['un gol olímpico', 'un récord mundial', 'un oro olímpico']],
  ['tarjeta roja', 'expulsión', ['un empate técnico', 'un saque de honor', 'un time-out']],
  ['VAR', 'revisión de video en fútbol', ['un estilo de crol', 'un tipo de raqueta', 'un casco de BMX']],
  ['fuera de lugar', 'regla de posición en ataque', ['regla de nado en piscina', 'regla de un putt', 'regla de un knock-out']],
  ['balón de oro', 'premio individual de fútbol', ['premio de ajedrez clásico', 'premio de dardos', 'premio de pesca']],
  ['Champions League', 'copa europea de clubes', ['serie mundial de béisbol', 'copa Davis solamente', 'mundial de atletismo']],
  ['Mundial femenino', 'copa del mundo de fútbol femenino', ['solo un slalom', 'solo un pentatlón', 'solo un rally']],
  ['tiempo reglamentario', '90 minutos en fútbol', ['4 sets fijos', '3 asaltos fijos', '18 hoyos']],
  ['prórroga', 'tiempo extra', ['un saque de meta', 'un cambio obligatorio de arquero', 'un córner automático']],
  ['penales decisivos', 'desempate desde los 11 metros', ['un salto con pértiga', 'un 100 metros', 'un ace']],
  ['cancha de básquet', 'dos aros', ['una piscina olímpica', 'un velódromo', 'un green']],
  ['cuartos en básquet', 'cuatro periodos', ['dos tiempos de 45', 'cinco sets', 'nueve entradas']],
  ['falta personal', 'contacto ilegal en básquet', ['un birdie', 'un try', 'un ace']],
  ['bandeja', 'entrada cerca del aro', ['un saque de banda', 'un drive de golf', 'un tackle']],
  ['tapón', 'bloquear un tiro', ['un córner', 'un putt', 'un relevo']],
  ['pase de gol en fútbol', 'asistencia', ['un knock-out', 'un ace de tenis', 'un jonrón']],
  ['hat-trick', 'tres goles de un jugador', ['tres aces seguidos en golf', 'tres sets de ajedrez', 'tres vueltas de F1']],
  ['autogol', 'gol en la propia portería', ['un triple propio', 'un ace propio', 'un try propio de tenis']],
  ['valla invicta', 'no recibir goles', ['no sacar aces', 'no encestar', 'no batear']],
  ['ciclismo de ruta', 'se corre en carretera', ['se nada en piscina', 'se boxea en ring', 'se juega en arcilla']],
  ['contrarreloj', 'cada ciclista contra el reloj', ['un 2 vs 2 de tenis', 'un asalto', 'un set de voleibol']],
  ['Giro de Italia', 'carrera de ciclismo', ['un slam de golf', 'un mundial de rugby 7', 'una copa Davis']],
  ['Vuelta a España', 'carrera de ciclismo', ['un abierto de Australia', 'un Super Bowl', 'un All-Star NBA']],
  ['Tour Colombia', 'carrera por etapas en Colombia', ['un Roland Garros', 'un Wimbledon', 'un US Open de tenis']],
  ['BMX olímpico', 'bicicletas en pista de saltos', ['remo en lago', 'vela en mar', 'clavados en plataforma']],
  ['patinaje de carreras', 'fuerte en Colombia', ['críquet test', 'hurling', 'lacrosse universitario']],
  ['tejo', 'deporte tradicional colombiano', ['un estilo de crol', 'un golpe de golf', 'un saque de rugby']],
  ['coleo', 'deporte llanero', ['un slalom alpino', 'un curling', 'un luge']],
  ['guantes de boxeo', 'protegen las manos', ['se usan para nadar crol', 'se usan para un putt', 'se usan para un ace']],
  ['round', 'asalto de boxeo', ['un set de ajedrez rápido', 'un hoyo de golf', 'una entrada de béisbol']],
  ['peso pluma', 'categoría de boxeo', ['un estilo de braza', 'un tipo de red', 'un casco de F1']],
  ['meta en atletismo', 'línea de llegada', ['un córner', 'un saque de honor', 'un time-out']],
  ['salida falsa', 'adelantarse al disparo', ['un gol olímpico', 'un triple', 'un ace']],
  ['récord mundial', 'la mejor marca de la historia', ['un empate local', 'un saque de banda', 'un cambio']],
  ['medalla de oro', 'primer lugar olímpico', ['cuarto lugar', 'un walkover', 'un empate técnico obligatorio']],
  ['antorcha olímpica', 'símbolo de los Juegos', ['un VAR', 'un offside', 'un birdie']],
  ['juramento olímpico', 'promesa de juego limpio', ['un córner', 'un penalty kick', 'un slam dunk']],
  ['dopaje', 'uso prohibido de sustancias', ['un saque de meta', 'un time-out táctico', 'un cambio de calzado']],
  ['fair play', 'juego limpio', ['un autogol forzado', 'una tarjeta roja táctica', 'un stalling']],
];

const HARD_HISTORY = [
  ['¿Qué documento rige a Colombia desde 1991?', 'la Constitución Política', ['las Leyes de Indias', 'el Código de Hammurabi', 'la Carta Magna inglesa de 1215'], 'La Constitución de 1991 es la norma superior vigente.'],
  ['¿Qué batalla consolidó la independencia de la Nueva Granada en 1819?', 'Boyacá', ['Waterloo', 'Gettysburg', 'Estalingrado'], 'Boyacá fue decisiva en la campaña libertadora.'],
  ['¿Qué país sudamericano proclamó su independencia en 1804 como república negra?', 'Haití', ['Chile', 'Uruguay', 'Paraguay'], 'Haití se independizó en 1804 tras la revolución de esclavos.'],
  ['¿Qué tratado de 1494 repartió tierras americanas entre España y Portugal?', 'Tordesillas', ['Versalles', 'Westfalia', 'Utrecht'], 'Tordesillas trazó una línea de reparto colonial.'],
  ['¿Qué imperio americano tenía su capital en Tenochtitlán?', 'el azteca', ['el romano', 'el otomano', 'el persa'], 'Tenochtitlán fue la capital mexica.'],
  ['¿Qué civilización construyó Machu Picchu?', 'la inca', ['la egipcia', 'la griega', 'la fenicia'], 'Machu Picchu es una ciudad inca en los Andes.'],
  ['¿Quién lideró la campaña libertadora en gran parte de Sudamérica?', 'Simón Bolívar', ['Napoleón', 'Washington', 'San Martín solamente en México'], 'Bolívar lideró la independencia de varios países andinos.'],
  ['¿Qué conflicto mundial comenzó en 1914?', 'la Primera Guerra Mundial', ['la Guerra Fría', 'la Guerra de Corea', 'la Guerra de Vietnam'], 'El conflicto de 1914-1918 es la Primera Guerra Mundial.'],
  ['¿Qué muro cayó en 1989 y simbolizó el fin de la Guerra Fría?', 'el de Berlín', ['el de Adriano', 'la muralla china', 'el de Hadriano en África'], 'La caída del Muro de Berlín ocurrió en 1989.'],
  ['¿En qué siglo se expandió con fuerza la Revolución Industrial?', 'XVIII y XIX', ['XI', 'XIV', 'XXI solamente'], 'La Revolución Industrial nació en el siglo XVIII y se extendió en el XIX.'],
  ['¿Qué organización nació en 1945 para promover la paz mundial?', 'la ONU', ['la FIFA', 'la OTAN solamente cultural', 'la UNESCO solamente deportiva'], 'La ONU se creó tras la Segunda Guerra Mundial.'],
  ['¿Qué misión llevó humanos a la Luna en 1969?', 'Apolo 11', ['Voyager 1', 'Sputnik 2', 'Curiosity'], 'Armstrong y Aldrin llegaron con Apolo 11.'],
  ['¿Qué proceso unió a varios países andinos bajo Bolívar a inicios del siglo XIX?', 'la Gran Colombia', ['el Sacro Imperio', 'la Liga Hanseática', 'el Pacto de Varsovia'], 'La Gran Colombia reunió a Nueva Granada, Venezuela y Quito.'],
  ['¿Qué guerra civil colombiana ocurrió entre 1899 y 1902?', 'la de los Mil Días', ['la Guerra del Pacífico', 'la Guerra de Secesión', 'la Guerra de los Cien Años'], 'La Guerra de los Mil Días enfrentó a liberales y conservadores.'],
  ['¿Qué pacto de 1958 alternó el poder entre dos partidos en Colombia?', 'el Frente Nacional', ['el New Deal', 'la Perestroika', 'el Plan Marshall'], 'El Frente Nacional pactó la alternancia liberal-conservadora.'],
  ['¿Qué imperio europeo dominó gran parte de América entre los siglos XVI y XIX?', 'el español', ['el mongol', 'el azteca tardío', 'el zulu'], 'España estableció virreinatos en América.'],
  ['¿Qué movimiento intelectual del siglo XVIII defendió la razón y los derechos?', 'la Ilustración', ['el Romanticismo tardío solamente', 'el Futurismo', 'el Dadaísmo'], 'La Ilustración influyó en las independencias.'],
  ['¿Qué ciudad fue capital del Virreinato de la Nueva Granada?', 'Santafé de Bogotá', ['Lima solamente', 'México-Tenochtitlán', 'Buenos Aires del Virreinato del Río de la Plata exclusivamente'], 'El virreinato neogranadino tuvo sede en Santafé.'],
  ['¿Qué acontecimiento de 1789 transformó a Francia y a Europa?', 'la Revolución francesa', ['la Revolución Meiji', 'la Revolución verde', 'la Revolución industrial china'], 'La Revolución francesa comenzó en 1789.'],
  ['¿Qué conflicto de 1939 a 1945 involucró a casi todo el planeta?', 'la Segunda Guerra Mundial', ['la Guerra de Crimea', 'la Guerra de los Siete Años', 'la Guerra del Opio'], 'La Segunda Guerra Mundial duró de 1939 a 1945.'],
  ['¿Qué líder sudafricano simbolizó el fin del apartheid?', 'Nelson Mandela', ['Patrice Lumumba solamente', 'Kwame Nkrumah solamente', 'Jomo Kenyatta solamente'], 'Mandela fue electo presidente en 1994.'],
  ['¿Qué canal inauguró en 1914 un atajo entre Atlántico y Pacífico?', 'el de Panamá', ['el de Suez solamente africano', 'el de Kiel', 'el de Corinto'], 'El Canal de Panamá une dos océanos.'],
  ['¿Qué imperio cayó en 476 en Occidente?', 'el romano de Occidente', ['el otomano de 1922 solamente', 'el británico de 1947', 'el inca de 1533 solamente'], '476 marca el fin convencional de la Edad Antigua en Occidente.'],
  ['¿Qué tecnología de Gutenberg cambió la difusión del saber?', 'la imprenta de tipos móviles', ['el telégrafo', 'la radio', 'el transistor'], 'La imprenta multiplicó los libros en Europa.'],
  ['¿Qué viaje de 1492 conectó de forma permanente Europa y América?', 'el de Colón', ['el de Cook al Pacífico', 'el de Amundsen al Polo', 'el de Magallanes ya completo en 1492'], 'Colón llegó a islas del Caribe en 1492.'],
  ['¿Qué virreinato español tuvo capital en Lima?', 'el del Perú', ['el de Nueva España exclusivamente', 'el del Río de la Plata en 1535', 'el de Brasil portugués'], 'Lima fue sede del Virreinato del Perú.'],
  ['¿Qué independencia se recuerda en México con el Grito de Dolores?', 'la de 1810', ['la de 1776', 'la de 1804', 'la de 1824 solamente peruana'], 'Hidalgo inició el movimiento en 1810.'],
  ['¿Qué batalla de 1824 selló la independencia sudamericana del dominio español?', 'Ayacucho', ['Trafalgar', 'Lepanto', 'Midway'], 'Ayacucho fue la derrota final del ejército realista en el Perú.'],
  ['¿Qué organización europea se profundizó con Maastricht en 1993?', 'la Unión Europea', ['la Liga de Naciones', 'el Comecon', 'la OEA'], 'El Tratado de Maastricht creó la Unión Europea.'],
  ['¿Qué crisis de 1962 puso al mundo cerca de una guerra nuclear?', 'la de los misiles en Cuba', ['la Crisis del 29', 'la Crisis del petróleo de 1973 solamente', 'la Crisis asiática de 1997'], 'EE. UU. y la URSS se enfrentaron por misiles en Cuba.'],
];

const HARD_SCIENCE = [
  ['¿Qué orgánulo realiza la fotosíntesis en las plantas?', 'el cloroplasto', ['la mitocondria solamente animal', 'el ribosoma', 'el lisosoma'], 'Los cloroplastos contienen clorofila.'],
  ['¿Qué ley describe que F = m·a?', 'la segunda ley de Newton', ['la ley de Ohm', 'la ley de Hooke', 'la ley de Coulomb solamente eléctrica'], 'La aceleración es proporcional a la fuerza neta.'],
  ['¿Qué partícula del núcleo no tiene carga?', 'el neutrón', ['el protón', 'el electrón', 'el fotón'], 'El neutrón es eléctricamente neutro.'],
  ['¿Cuál es el pH aproximado del agua pura a 25 °C?', '7', ['1', '10', '14'], 'El agua pura es neutra, cerca de pH 7.'],
  ['¿Qué gas es más abundante en el aire seco?', 'el nitrógeno', ['el oxígeno', 'el dióxido de carbono', 'el argón como mayoritario'], 'El aire seco tiene cerca de 78% de nitrógeno.'],
  ['¿Qué planeta es un gigante helado junto con Urano?', 'Neptuno', ['Marte', 'Mercurio', 'Venus'], 'Urano y Neptuno son gigantes helados.'],
  ['¿Qué tipo de onda es el sonido en el aire?', 'longitudinal', ['transversal electromagnética', 'gravitacional pura', 'estacionaria de luz'], 'El sonido comprime y rareface el aire.'],
  ['¿Qué fenómeno desvía la luz al cambiar de medio?', 'la refracción', ['la sublimación', 'la oxidación', 'la fermentación'], 'Un lápiz se ve quebrado en un vaso por refracción.'],
  ['¿Qué molécula almacena la información genética?', 'el ADN', ['el ATP solamente energético', 'la hemoglobina', 'la celulosa'], 'El ADN guarda las instrucciones hereditarias.'],
  ['¿Qué grupo de vertebrados incluye ranas y salamandras?', 'los anfibios', ['los reptiles exclusivamente', 'los peces óseos', 'las aves'], 'Los anfibios suelen tener fase larval acuática.'],
  ['¿Qué capa de la Tierra es líquida y metálica bajo el manto?', 'el núcleo externo', ['la corteza continental', 'la troposfera', 'la hidrosfera'], 'El núcleo externo líquido genera el campo magnético.'],
  ['¿Qué escala mide la magnitud de un sismo de forma logarítmica moderna?', 'la de magnitud de momento', ['la de Beaufort', 'la de Mohs', 'la de Richter exclusivamente histórica'], 'Hoy se usa sobre todo la magnitud de momento.'],
  ['¿Qué proceso convierte un sólido en gas sin pasar por líquido?', 'la sublimación', ['la condensación', 'la solidificación', 'la fusión'], 'El hielo seco se sublima.'],
  ['¿Qué vitamina se asocia con los cítricos y el escorbuto?', 'la C', ['la D solamente solar', 'la K de coagulación exclusiva', 'la B12 de origen animal exclusiva'], 'La vitamina C previene el escorbuto.'],
  ['¿Qué organelo produce la mayor parte del ATP celular?', 'la mitocondria', ['el aparato de Golgi', 'el retículo liso', 'la pared celular'], 'La respiración celular ocurre sobre todo en mitocondrias.'],
  ['¿Qué ley dice que la presión de un gas baja si sube el volumen (T constante)?', 'Boyle-Mariotte', ['Charles solamente', 'Gay-Lussac de temperaturas fijas distintas', 'Avogadro de volúmenes iguales'], 'A temperatura constante, P y V son inversamente proporcionales.'],
  ['¿Qué tipo de enlace une Na y Cl en la sal de mesa?', 'iónico', ['covalente no polar puro', 'metálico de cobre', 'puente de hidrógeno solamente'], 'NaCl forma iones Na+ y Cl-.'],
  ['¿Qué radiación ultravioleta filtra sobre todo la capa de ozono?', 'UV-B', ['microondas de horno', 'ondas de radio AM', 'rayos gamma de un núcleo'], 'El ozono estratosférico reduce el UV-B dañino.'],
  ['¿Qué unidad mide la fuerza en el SI?', 'el newton', ['el joule', 'el watt', 'el pascal'], 'Un newton es 1 kg·m/s².'],
  ['¿Qué unidad mide la energía en el SI?', 'el julio', ['el voltio', 'el ohmio', 'el tesla'], 'El julio (joule) es la unidad de energía.'],
  ['¿Qué sangre transporta oxígeno gracias a la hemoglobina?', 'la de los glóbulos rojos', ['el plasma sin células', 'la linfa solamente', 'el líquido cefalorraquídeo'], 'Los eritrocitos llevan hemoglobina.'],
  ['¿Qué planeta tiene un día más largo que su año?', 'Venus', ['Júpiter', 'Mercurio en sentido estricto de traslación más corta siempre', 'Saturno'], 'Venus rota muy lento: su día solar es muy largo.'],
  ['¿Qué satélite de Saturno tiene atmósfera densa y mares de metano?', 'Titán', ['Europa de Júpiter solamente helada', 'Ganimedes sin mares de metano', 'Fobos'], 'Titán es el satélite más atmosférico del sistema solar.'],
  ['¿Qué teoría explica la diversidad de las especies por selección natural?', 'la evolución de Darwin y Wallace', ['el fijismo', 'la generación espontánea', 'el catastrofismo exclusivo de Cuvier'], 'La selección natural favorece rasgos que ayudan a sobrevivir.'],
  ['¿Qué ciclo biogeoquímico incluye fotosíntesis y respiración?', 'el del carbono', ['el del oro', 'el del helio estelar solamente', 'el del uranio de minas'], 'El CO2 entra a las plantas y sale en la respiración.'],
  ['¿Qué tipo de energía usan las plantas para la fotosíntesis?', 'la lumínica', ['la cinética de un auto', 'la eólica de un molino humano', 'la geotérmica de un géiser exclusivamente'], 'La clorofila capta luz visible.'],
  ['¿Qué aparato mide la presión atmosférica?', 'el barómetro', ['el amperímetro', 'el higrómetro solamente de humedad', 'el sismógrafo'], 'El barómetro indica altas y bajas presiones.'],
  ['¿Qué aparato registra sismos?', 'el sismógrafo', ['el telescopio', 'el potenciómetro', 'el odómetro'], 'El sismógrafo traza las ondas sísmicas.'],
  ['¿Qué porcentaje aproximado de agua tiene el cuerpo humano?', 'cerca de 60%', ['cerca de 5%', 'cerca de 15%', 'cerca de 95%'], 'El agua es el componente mayoritario del cuerpo.'],
  ['¿Qué grupo sanguíneo es donante universal de glóbulos rojos?', 'O negativo', ['AB positivo', 'A positivo', 'B positivo'], 'O negativo suele usarse en urgencias como donante de eritrocitos.'],
];

const HARD_CULTURE = [
  ['¿Qué escritor colombiano recibió el Nobel de Literatura en 1982?', 'Gabriel García Márquez', ['Álvaro Mutis', 'Rafael Pombo', 'José Eustasio Rivera'], 'García Márquez ganó el Nobel por su obra narrativa.'],
  ['¿Qué pueblo ancestral habita la península de La Guajira?', 'los wayuu', ['los mapuches de Chile exclusivamente', 'los guaraníes del Paraguay exclusivamente', 'los quechuas del Cuzco exclusivamente'], 'Los wayuu son el pueblo indígena más numeroso de Colombia.'],
  ['¿Qué ciudad colombiana es famosa por su carnaval patrimonio de la UNESCO?', 'Barranquilla', ['Sogamoso', 'Honda', 'Girón'], 'El Carnaval de Barranquilla es patrimonio inmaterial.'],
  ['¿Qué ritmo mezcla caja, guacharaca y acordeón?', 'el vallenato', ['el merengue dominicano exclusivo', 'el son cubano exclusivo', 'el mariachi'], 'El vallenato nació en la Costa Caribe colombiana.'],
  ['¿Qué región es reconocida por el paisaje cultural cafetero?', 'el Eje Cafetero', ['La Guajira desértica', 'San Andrés coralino solamente', 'el Amazonas de Leticia solamente'], 'El Paisaje Cultural Cafetero es patrimonio de la UNESCO.'],
  ['¿Qué lengua indígena andina se habla aún en partes de Colombia, Ecuador, Perú y Bolivia?', 'el quechua', ['el euskera', 'el bretón', 'el galés'], 'El quechua es una lengua originaria de los Andes.'],
  ['¿Qué ciudad alberga el Museo del Oro del Banco de la República?', 'Bogotá', ['Armenia', 'Sincelejo', 'Riohacha'], 'El Museo del Oro está en Bogotá.'],
  ['¿Qué pueblo cimarrón de Bolívar es patrimonio de la UNESCO?', 'San Basilio de Palenque', ['Villa de Leyva solamente colonial', 'Barichara solamente', 'Mompox solamente fluvial'], 'Palenque fue el primer pueblo libre de América.'],
  ['¿Qué instrumento de viento andino se fabrica tradicionalmente de caña?', 'la quena', ['el clarinete de jazz exclusivo', 'la gaita escocesa', 'el saxofón'], 'La quena es una flauta andina.'],
  ['¿Qué baile de pareja es símbolo nacional asociado al Caribe colombiano?', 'la cumbia', ['el vals de Viena', 'el tango finlandés', 'el breakdance'], 'La cumbia es un baile mestizo del Caribe colombiano.'],
  ['¿Qué archipiélago colombiano tiene raíz raizal e idioma criollo?', 'San Andrés y Providencia', ['Malpelo solamente rocosa', 'Gorgona solamente pacífica', 'las islas del Rosario continentales'], 'La cultura raizal es propia del archipiélago.'],
  ['¿Qué río de colores está en la Sierra de la Macarena?', 'Caño Cristales', ['el Nilo', 'el Danubio', 'el Yangtsé'], 'Caño Cristales es famoso por sus plantas acuáticas de colores.'],
  ['¿Qué tradición del 7 de diciembre ilumina calles colombianas?', 'el día de las velitas', ['Halloween', 'el Día del Trabajo', 'el Día de la Tierra'], 'Se encienden velas en honor a la Inmaculada.'],
  ['¿Qué plato bogotano lleva tres papas, pollo y mazorca?', 'el ajiaco', ['el ceviche', 'la paella', 'el mole'], 'El ajiaco santafereño es típico de la sabana.'],
  ['¿Qué sombrero trenzado es símbolo nacional de Colombia?', 'el vueltiao', ['el bombín inglés', 'el chupalla chileno exclusivo', 'el sombrero cordobés español exclusivo'], 'El sombrero vueltiao es típico de Córdoba y Sucre.'],
  ['¿Qué feria de agosto es emblema de Medellín?', 'la Feria de las Flores', ['el Oktoberfest de Múnich', 'el Carnaval de Venecia', 'la Tomatina'], 'Se destaca el desfile de silleteros.'],
  ['¿Qué ciudad amurallada del Caribe es patrimonio mundial?', 'Cartagena', ['Buenaventura', 'Turbo', 'Coveñas'], 'El centro histórico de Cartagena es patrimonio de la UNESCO.'],
  ['¿Qué pueblo de Nariño celebra el Carnaval de Negros y Blancos?', 'Pasto', ['Valledupar', 'Montería', 'Florencia'], 'El carnaval pastuso es patrimonio inmaterial.'],
  ['¿Qué bebida caliente andina es emblema de exportación colombiana?', 'el café', ['el sake', 'el vodka', 'el tequila exclusivo de Colombia'], 'Colombia es uno de los grandes productores de café suave.'],
  ['¿Qué comida de maíz es común en Colombia y Venezuela?', 'la arepa', ['el bagel', 'el croissant', 'el pretzel']],
  ['¿Qué escritor peruano es conocido por La ciudad y los perros?', 'Mario Vargas Llosa', ['Julio Cortázar', 'Jorge Luis Borges', 'Octavio Paz'], 'Vargas Llosa también fue Nobel de Literatura.'],
  ['¿Qué poeta chileno escribió Veinte poemas de amor?', 'Pablo Neruda', ['Gabriela Mistral solamente en esa obra', 'Nicanor Parra exclusivamente', 'Vicente Huidobro exclusivamente'], 'Neruda es uno de los poetas más leídos de América.'],
  ['¿Qué civilización andina hablaba quechua y tenía el Cuzco como centro?', 'la inca', ['la maya de Yucatán exclusivamente', 'la olmeca', 'la tolteca'], 'El Tahuantinsuyo tuvo capital en el Cuzco.'],
  ['¿Qué fiesta brasileña es famosa por sus escuelas de samba?', 'el carnaval de Río', ['el Día de Acción de Gracias', 'el Hogmanay', 'el Songkran'], 'Río es mundialmente conocido por su carnaval.'],
  ['¿Qué música rioplatense nació en Buenos Aires y Montevideo?', 'el tango', ['el flamenco', 'el fado', 'el reggae'], 'El tango es patrimonio del Río de la Plata.'],
  ['¿Qué organización declara patrimonios culturales de la humanidad?', 'la UNESCO', ['la FIFA', 'la OMS deportiva', 'la OPEP cultural'], 'La UNESCO vela por el patrimonio mundial.'],
  ['¿Qué idioma criollo se habla junto al inglés en San Andrés?', 'el criollo sanandresano', ['el afrikáans', 'el papiamento exclusivo de Colombia andina', 'el criollo de Luisiana'], 'El creole raizal es parte de la identidad insular.'],
  ['¿Qué mito muisca se asocia a ofrendas de oro en una laguna?', 'El Dorado', ['el Minotauro', 'el Quetzalcóatl exclusivo azteca de esa laguna', 'la Atlántida griega'], 'La ceremonia del zipa inspiró la leyenda de El Dorado.'],
  ['¿Qué ciudad es capital cultural reconocida por su teatro y museos en el centro andino colombiano?', 'Bogotá', ['Leticia como capital andina', 'San Andrés como capital andina', 'Riohacha andina'], 'Bogotá concentra grandes museos y el Teatro Colón.'],
  ['¿Qué prenda de lana andina se usa en el frío de Boyacá y Cundinamarca?', 'la ruana', ['el kimono', 'el kilt', 'el poncho mexicano exclusivo de esas tierras'], 'La ruana es típica de los Andes colombianos.'],
];

const HARD_ART = [
  ['¿Quién pintó el Guernica en 1937?', 'Pablo Picasso', ['Salvador Dalí', 'Joan Miró', 'Diego Velázquez'], 'Guernica denuncia el bombardeo de la Guerra Civil española.'],
  ['¿Qué movimiento artístico fragmenta objetos en geometría?', 'el cubismo', ['el impresionismo', 'el romanticismo', 'el barroco'], 'Picasso y Braque impulsaron el cubismo.'],
  ['¿Qué pintor holandés es autor de La noche estrellada?', 'Vincent van Gogh', ['Rembrandt', 'Vermeer', 'Mondrian solamente geométrico'], 'Van Gogh pintó La noche estrellada en 1889.'],
  ['¿Qué artista colombiano es célebre por sus figuras voluminosas?', 'Fernando Botero', ['Alejandro Obregón solamente abstracto', 'Débora Arango solamente mural', 'Andrés de Santa María exclusivamente'], 'El boterismo exagera el volumen de las figuras.'],
  ['¿Qué técnica usa pigmentos diluidos en agua sobre papel?', 'la acuarela', ['el óleo de empaste grueso exclusivo', 'el temple de huevo mural exclusivo', 'el fresco húmedo de muro'], 'La acuarela es transparente y luminosa.'],
  ['¿Qué escultor renacentista talló el David en mármol?', 'Miguel Ángel', ['Donatello solamente el David en bronce de otra época exclusiva', 'Bernini del barroco exclusivamente', 'Rodin del XIX exclusivamente'], 'El David de Miguel Ángel está en Florencia.'],
  ['¿Qué pintora mexicana es famosa por sus autorretratos?', 'Frida Kahlo', ['Remedios Varo solamente', 'Leonora Carrington solamente', 'Georgia O’Keeffe solamente'], 'Kahlo convirtió su vida en tema pictórico.'],
  ['¿Qué estilo del siglo XVII busca dramatismo y ornamentación?', 'el barroco', ['el minimalismo', 'el neoplasticismo', 'el constructivismo'], 'El barroco es teatral y recargado.'],
  ['¿Qué compositor escribió la Novena Sinfonía con el Himno a la alegría?', 'Beethoven', ['Mozart', 'Bach', 'Vivaldi'], 'La Novena de Beethoven incluye un coro.'],
  ['¿Qué clave musical se usa con más frecuencia para la mano derecha del piano?', 'la de sol', ['la de fa exclusivamente siempre', 'la de do en tercera siempre', 'ninguna clave'], 'La clave de sol sitúa el sol en la segunda línea.'],
  ['¿Qué obra de Velázquez muestra a la infanta Margarita y el propio pintor?', 'Las meninas', ['Las lanzas solamente', 'La rendición de Breda exclusivamente como única obra', 'El Cristo crucificado exclusivamente'], 'Las meninas cuelgan en el Museo del Prado.'],
  ['¿Qué pintor noruego creó El grito?', 'Edvard Munch', ['Gustav Klimt', 'Egon Schiele', 'Wassily Kandinsky'], 'El grito es un ícono del expresionismo.'],
  ['¿Qué vanguardia explora el mundo de los sueños, como Dalí?', 'el surrealismo', ['el realismo socialista', 'el hiperrealismo fotográfico exclusivo', 'el fauvismo de color plano exclusivo'], 'El surrealismo nace con Breton en 1924.'],
  ['¿Qué escuela alemana unió artesanía, arte y diseño industrial?', 'la Bauhaus', ['la Academia francesa del XVII exclusivamente', 'el Taller del Greco', 'la Escuela de Barbizon solamente paisajista'], 'La Bauhaus funcionó entre 1919 y 1933.'],
  ['¿Qué técnica mural se pinta sobre el revoque aún húmedo?', 'el fresco', ['el collage', 'el grabado al aguafuerte', 'la serigrafía'], 'El fresco se integra a la cal del muro.'],
  ['¿Qué instrumento colombiano de 12 cuerdas acompaña el bambuco?', 'el tiple', ['el sitar', 'el shamisen', 'el balalaika'], 'El tiple es emblemático de la música andina colombiana.'],
  ['¿Qué pintora colombiana abordó temas sociales con un estilo expresivo?', 'Débora Arango', ['Frida Kahlo mexicana exclusiva en esta pregunta', 'Tamara de Lempicka', 'Mary Cassatt'], 'Débora Arango pintó la realidad política colombiana.'],
  ['¿Qué artista colombiano es conocido por paisajes, cóndores y el Caribe?', 'Alejandro Obregón', ['Botero exclusivamente volumétrico en esta pregunta', 'Roda solamente', 'Grau solamente pop'], 'Obregón es una figura central del arte moderno colombiano.'],
  ['¿Qué elemento organiza el pulso en una partitura?', 'el compás', ['el barniz', 'el caballete', 'el lienzo'], 'El compás agrupa tiempos fuertes y débiles.'],
  ['¿Qué conjunto instrumental agrupa cuerdas, vientos y percusión?', 'la orquesta sinfónica', ['un cuarteto de rock exclusivo', 'una banda marcial solamente', 'un dúo de gaitas'], 'La orquesta sinfónica interpreta sinfonías y conciertos.'],
  ['¿Qué color se obtiene al mezclar rojo y azul?', 'morado o violeta', ['verde', 'naranja', 'marrón exclusivo siempre'], 'Rojo y azul dan un violeta.'],
  ['¿Qué perspectiva hace que las líneas paralelas parezcan juntarse?', 'la cónica o lineal', ['la axonométrica sin fuga', 'la isométrica pura', 'la caballera sin horizonte'], 'El punto de fuga crea profundidad.'],
  ['¿Qué movimiento captura la impresión de la luz al aire libre?', 'el impresionismo', ['el cubismo analítico', 'el suprematismo', 'el arte povera'], 'Monet y Renoir son impresionistas célebres.'],
  ['¿Qué templo griego de Atenas es ícono del arte clásico?', 'el Partenón', ['el Coliseo', 'el Panteón de Roma exclusivamente', 'Santa Sofía exclusivamente bizantina'], 'El Partenón está en la Acrópolis.'],
  ['¿Qué anfiteatro romano se usó para espectáculos públicos?', 'el Coliseo', ['el Partenón', 'Machu Picchu', 'Chichén Itzá exclusivamente maya'], 'El Coliseo está en Roma.'],
  ['¿Qué tipo de pintura representa objetos inanimados?', 'el bodegón', ['el retrato de corte', 'el paisaje marino exclusivo', 'la pintura de historia de batallas'], 'El bodegón muestra frutas, flores o utensilios.'],
  ['¿Qué arte escénico combina canto, orquesta y drama?', 'la ópera', ['el teatro del absurdo sin música', 'el monólogo stand-up', 'la performance muda exclusiva'], 'La ópera nació en Italia hacia 1600.'],
  ['¿Qué director de orquesta hace frente al público?', 'el que da la espalda a la platea y mira a los músicos', ['el solista de violín siempre', 'el tramoyista', 'el libretista'], 'El director coordina tempos y entradas.'],
  ['¿Qué técnica imprime una imagen desde una placa grabada?', 'el grabado', ['la acuarela directa', 'el fresco húmedo', 'el modelado en arcilla'], 'Xilografía, aguafuerte y litografía son tipos de grabado.'],
  ['¿Qué material de orfebrería precolombina llena el Museo del Oro?', 'el oro', ['el mármol de Carrara', 'el bronce griego exclusivo', 'el marfil gótico'], 'Las culturas muisca, tairona y quimbaya trabajaron el oro.'],
];

const HARD_SPORTS = [
  ['¿Cuántos jugadores de campo más el portero forman un equipo de fútbol?', '11', ['9', '13', '15'], 'El fútbol se juega 11 contra 11.'],
  ['¿Qué distancia oficial tiene un maratón?', '42,195 km', ['21,097 km', '10 km', '50 km'], 'El maratón olímpico mide 42,195 kilómetros.'],
  ['¿Cada cuántos años se celebran los Juegos Olímpicos de verano?', '4', ['2', '3', '6'], 'El ciclo olímpico de verano es de cuatro años.'],
  ['¿Qué ciclista colombiano ganó el Tour de Francia en 2019?', 'Egan Bernal', ['Nairo Quintana', 'Rigoberto Urán', 'Rafael Antonio Niño'], 'Bernal fue el primer latinoamericano en ganar el Tour.'],
  ['¿En qué deporte fue campeona olímpica Mariana Pajón?', 'BMX', ['atletismo', 'natación', 'halterofilia'], 'Pajón ganó oros olímpicos en BMX.'],
  ['¿Qué prueba de triple salto consagró a Caterine Ibargüen?', 'el atletismo', ['el salto ornamental', 'el pentatlón moderno exclusivo', 'la gimnasia artística'], 'Ibargüen fue campeona olímpica de triple salto.'],
  ['¿Cuántos sets se necesitan para ganar un partido de Grand Slam masculino en individuales?', '3 de 5', ['1 de 1', '2 de 3 siempre en todos los slams masculinos actuales', '4 de 7'], 'En individuales masculinos de Grand Slam se juega al mejor de cinco.'],
  ['¿Qué superficie tiene Wimbledon?', 'césped', ['arcilla', 'pista dura', 'sintética indoor exclusiva'], 'Wimbledon es el Grand Slam sobre hierba.'],
  ['¿Qué organización rige el fútbol mundial?', 'la FIFA', ['la FIBA', 'la FINA histórica solamente', 'la UCI'], 'La FIFA organiza las Copas del Mundo.'],
  ['¿A qué distancia se cobra un penal en fútbol?', '11 metros', ['9 metros', '16,5 metros', '7,32 metros'], 'El punto penal está a 11 metros de la portería.'],
  ['¿Cuántos jugadores hay por equipo en la cancha de voleibol indoor?', '6', ['5', '7', '11'], 'El voleibol de salón se juega 6 contra 6.'],
  ['¿Qué prueba combina natación, ciclismo y carrera a pie?', 'el triatlón', ['el decatlón', 'el heptatlón', 'el pentatlón antiguo griego exclusivo'], 'El orden olímpico es nadar, pedalear y correr.'],
  ['¿Qué deporte usa un disco o puck sobre hielo?', 'el hockey sobre hielo', ['el curling exclusivamente de piedras', 'el béisbol', 'el waterpolo'], 'El puck se golpea con un stick.'],
  ['¿Qué anotación de fútbol americano vale 6 puntos antes del extra?', 'el touchdown', ['el field goal de 3', 'el safety de 2', 'el extra point de 1'], 'El touchdown suma seis puntos.'],
  ['¿Qué golpe de tenis gana el punto de saque sin que el rival toque la pelota?', 'el ace', ['el drop shot', 'el lob', 'el passing shot en resto'], 'Un ace es un saque ganador directo.'],
  ['¿Desde dónde vale un triple en baloncesto?', 'más allá de la línea de tres', ['dentro del área restringida solamente', 'desde el saque de banda de fútbol', 'desde el punto penal'], 'La línea de triple está a 6,75 m en FIBA.'],
  ['¿Qué carrera por etapas es la más prestigiosa del ciclismo de ruta?', 'el Tour de Francia', ['la París-Dakar de autos', 'la Indy 500', 'la Boston Marathon'], 'El Tour es el Gran Vuelta más mediático.'],
  ['¿Qué arte marcial olímpico coreano destaca por patadas?', 'el taekwondo', ['el judo de proyección exclusiva', 'la esgrima', 'la lucha grecorromana'], 'El taekwondo es deporte olímpico desde Sídney 2000.'],
  ['¿Cuántos tiempos de 45 minutos tiene un partido de fútbol?', '2', ['3', '4', '1'], 'Se juegan dos tiempos de 45 minutos más el descuento.'],
  ['¿Qué nadador es plusmarquista histórico de múltiples oros olímpicos?', 'Michael Phelps', ['Usain Bolt', 'Michael Jordan', 'Roger Federer'], 'Phelps acumula el récord de oros olímpicos individuales y de relevos.'],
  ['¿Qué prueba atlética recorre 42,195 km?', 'el maratón', ['los 10 000 metros pista', 'la media maratón exclusiva', 'los 5000 metros'], 'Maratón no es una vuelta a la pista.'],
  ['¿Qué deporte tradicional colombiano lanza un tejo a una mecha?', 'el tejo', ['el coleo', 'la chaza exclusiva', 'el ullu'], 'El tejo es deporte nacional de Colombia.'],
  ['¿Qué ciclista colombiano es célebre por podios en Grandes Vueltas además de Bernal?', 'Nairo Quintana', ['James Rodríguez', 'Falcao', 'Juan Pablo Ángel'], 'Nairo ganó Giro y Vuelta a España.'],
  ['¿Qué significa un hat-trick en fútbol?', 'tres goles de un mismo jugador', ['tres asistencias solamente', 'tres tarjetas', 'tres penales atajados solamente'], 'El hat-trick es una tripleta goleadora.'],
  ['¿Qué tecnología ayuda al árbitro a revisar jugadas en el fútbol moderno?', 'el VAR', ['el Hawk-Eye exclusivo de tenis en esta pregunta', 'el goal-line solamente de rugby', 'el replay de básquet NBA exclusivo'], 'VAR significa Video Assistant Referee.'],
  ['¿Cuántos Grand Slam hay en el tenis anual?', '4', ['2', '3', '5'], 'Australia, Roland Garros, Wimbledon y US Open.'],
  ['¿Qué estilo de natación es el más rápido en piscina?', 'el crol o libre', ['la braza', 'la espalda siempre más rápida', 'la mariposa siempre más rápida que el libre'], 'El estilo libre de crol es el de mayor velocidad.'],
  ['¿Qué prueba de campo lanza un implemento de 800 g los varones élite?', 'la jabalina', ['el peso de 7,26 kg', 'el disco de 2 kg', 'el martillo'], 'La jabalina masculina pesa 800 gramos.'],
  ['¿Cada cuántos años se celebran los Juegos Olímpicos de invierno?', '4', ['1', '2', '8'], 'Los Juegos de invierno también siguen un ciclo de cuatro años.'],
];

module.exports = {
  EXTRA_HISTORY_EVENTS,
  EXTRA_SCIENCE,
  EXTRA_CULTURE,
  EXTRA_ART,
  EXTRA_SPORTS,
  HARD_HISTORY,
  HARD_SCIENCE,
  HARD_CULTURE,
  HARD_ART,
  HARD_SPORTS,
};
